import type { ClientPlatformRepository } from "@/src/modules/client-platform/application/contracts";
import type { ClientDevice, EncryptedPushSubscription } from "@/src/modules/client-platform/domain/client-device";
import type { TransactionalDatabase } from "@/src/platform/database/executor";

type DeviceRow = { id:string; tenant_id:string; user_id:string; installation_id:string; display_name:string; client_type:ClientDevice["clientType"]; platform:string; app_version:string; trust_level:ClientDevice["trustLevel"]; status:ClientDevice["status"]; push_enabled:boolean; last_seen_at:string|Date; registered_at:string|Date; revoked_at:string|Date|null; version:number };
const iso = (value: string | Date) => new Date(value).toISOString();
function mapDevice(row: DeviceRow): ClientDevice { return { id:row.id,tenantId:row.tenant_id,userId:row.user_id,installationId:row.installation_id,displayName:row.display_name,clientType:row.client_type,platform:row.platform,appVersion:row.app_version,trustLevel:row.trust_level,status:row.status,pushEnabled:row.push_enabled,lastSeenAt:iso(row.last_seen_at),registeredAt:iso(row.registered_at),revokedAt:row.revoked_at?iso(row.revoked_at):undefined,version:row.version }; }

export class PostgresClientPlatformRepository implements ClientPlatformRepository {
  constructor(private readonly database: TransactionalDatabase) {}
  async listDevices(tenantId: string, userId: string): Promise<ClientDevice[]> { return this.database.withTenant(tenantId, async (db) => (await db.query<DeviceRow>("SELECT * FROM client_devices WHERE user_id=$1 ORDER BY last_seen_at DESC",[userId])).map(mapDevice)); }
  async getDevice(tenantId: string, deviceId: string): Promise<ClientDevice | undefined> { return this.database.withTenant(tenantId, async (db) => { const rows=await db.query<DeviceRow>("SELECT * FROM client_devices WHERE id=$1",[deviceId]); return rows[0]?mapDevice(rows[0]):undefined; }); }
  async getByInstallation(tenantId: string, userId: string, installationId: string): Promise<ClientDevice | undefined> { return this.database.withTenant(tenantId, async (db) => { const rows=await db.query<DeviceRow>("SELECT * FROM client_devices WHERE user_id=$1 AND installation_id=$2",[userId,installationId]); return rows[0]?mapDevice(rows[0]):undefined; }); }
  async saveDevice(device: ClientDevice): Promise<void> { await this.database.withTenant(device.tenantId, async (db) => { await db.query(`INSERT INTO client_devices(id,tenant_id,user_id,installation_id,display_name,client_type,platform,app_version,trust_level,status,push_enabled,last_seen_at,registered_at,revoked_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET display_name=excluded.display_name,client_type=excluded.client_type,platform=excluded.platform,app_version=excluded.app_version,trust_level=excluded.trust_level,status=excluded.status,push_enabled=excluded.push_enabled,last_seen_at=excluded.last_seen_at,revoked_at=excluded.revoked_at,version=excluded.version`,[device.id,device.tenantId,device.userId,device.installationId,device.displayName,device.clientType,device.platform,device.appVersion,device.trustLevel,device.status,device.pushEnabled,device.lastSeenAt,device.registeredAt,device.revokedAt??null,device.version]); }); }
  async savePushSubscription(subscription: EncryptedPushSubscription): Promise<void> { await this.database.withTenant(subscription.tenantId, async (db) => { await db.query(`INSERT INTO client_push_subscriptions(id,tenant_id,user_id,device_id,endpoint_digest,encrypted_payload,initialization_vector,authentication_tag,key_ref,status,created_at,revoked_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(tenant_id,endpoint_digest) DO UPDATE SET user_id=excluded.user_id,device_id=excluded.device_id,encrypted_payload=excluded.encrypted_payload,initialization_vector=excluded.initialization_vector,authentication_tag=excluded.authentication_tag,key_ref=excluded.key_ref,status='active',revoked_at=NULL,version=client_push_subscriptions.version+1`,[subscription.id,subscription.tenantId,subscription.userId,subscription.deviceId,subscription.endpointDigest,subscription.encryptedPayload,subscription.initializationVector,subscription.authenticationTag,subscription.keyRef,subscription.status,subscription.createdAt,subscription.revokedAt??null,subscription.version]); }); }
  async revokePushSubscriptions(tenantId: string, deviceId: string, revokedAt: string): Promise<void> { await this.database.withTenant(tenantId, async (db) => { await db.query("UPDATE client_push_subscriptions SET status='revoked',revoked_at=$2,version=version+1 WHERE device_id=$1 AND status='active'",[deviceId,revokedAt]); }); }
}
