// Requirements: PR-004, AR-011, AR-012, SR-001, SR-002
import { describe,expect,it } from "vitest";
import { GET as bootstrap } from "@/app/api/v1/client/bootstrap/route";
import { GET as listDevices,POST as registerDevice } from "@/app/api/v1/client/devices/route";
import { POST as revokeDevice } from "@/app/api/v1/client/devices/[id]/revoke/route";

describe("client platform API",()=>{
  it("registers, bootstraps, lists and revokes the current user's installation",async()=>{const installationId=crypto.randomUUID();const request=new Request("http://localhost/api/v1/client/devices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({installationId,displayName:"API 测试设备",clientType:"web_pwa",platform:"Test Browser",appVersion:"0.9.0"})});const registered=await registerDevice(request);expect(registered.status).toBe(201);const registeredBody=await registered.json();const deviceId=registeredBody.data.id;const bootstrapped=await bootstrap(new Request(`http://localhost/api/v1/client/bootstrap?installationId=${installationId}&appVersion=0.9.0`));expect(bootstrapped.status).toBe(200);expect((await bootstrapped.json()).data.device).toMatchObject({id:deviceId,trustLevel:"unmanaged"});const listed=await listDevices(new Request("http://localhost/api/v1/client/devices"));expect((await listed.json()).data.some((device:{id:string})=>device.id===deviceId)).toBe(true);const revoked=await revokeDevice(new Request(`http://localhost/api/v1/client/devices/${deviceId}/revoke`,{method:"POST"}),{params:Promise.resolve({id:deviceId})});expect(await revoked.json()).toMatchObject({data:{id:deviceId,status:"revoked"}});});
  it("rejects attempts to self-assert tenant, actor or attested trust",async()=>{const response=await registerDevice(new Request("http://localhost/api/v1/client/devices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({installationId:crypto.randomUUID(),displayName:"恶意设备",clientType:"web_pwa",platform:"Test",appVersion:"0.9.0",trustLevel:"attested",tenantId:"attacker",userId:"attacker"})}));expect(response.status).toBe(422);});
});
