// Requirements: PR-008, AR-002, AR-003, AR-004, AR-012, SR-002, SR-005, AC-008
import { readFile } from "node:fs/promises";
import path from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { afterEach,beforeEach,describe,expect,it } from "vitest";
import type { DatabaseExecutor,SqlPrimitive,TransactionalDatabase } from "@/src/platform/database/executor";
import { PostgresClientPlatformRepository } from "@/src/modules/client-platform/infrastructure/postgres-repository";
import { ClientPlatformService } from "@/src/modules/client-platform/application/service";
import { createDevelopmentRequestContext,DEMO_MANAGER_ID,DEMO_TENANT_ID } from "@/src/platform/context/development-context";

describe("Postgres client platform",()=>{let database:PGlite;let service:ClientPlatformService;let repository:PostgresClientPlatformRepository;
beforeEach(async()=>{database=new PGlite();for(const file of ["0001_foundation.sql","0002_management_loop.sql","0003_agent_platform.sql","0004_connector_platform.sql","0005_workflow_knowledge.sql","0006_strategy_organization_talent.sql","0007_client_platform.sql","0008_security_hardening.sql","0009_atomic_audit.sql","0010_immutable_audit.sql","0011_enterprise_governance.sql","0012_enterprise_acceptance.sql","0013_connector_test_notifications.sql"])await database.exec(await readFile(path.resolve("src/platform/database/migrations",file),"utf8"));const executor:DatabaseExecutor={async query<T extends Record<string,unknown>>(sql:string,params:SqlPrimitive[]=[]){return(await database.query<T>(sql,params as never[])).rows;}};const adapter:TransactionalDatabase={...executor,async withTenant<T>(tenantId:string,work:(scoped:DatabaseExecutor)=>Promise<T>){await database.query("SELECT set_config('app.tenant_id',$1,false)",[tenantId]);return work(executor);},async close(){await database.close();}};repository=new PostgresClientPlatformRepository(adapter);service=new ClientPlatformService(repository,{minimumVersion:"0.9.0",managedDeviceRequired:false,offlineDrafts:"internal",pushEnabled:true,pushPublicKey:"public",draftRetentionDays:7});await database.query("INSERT INTO tenants(id,slug,name,status) VALUES($1,'demo','Demo','active')",[DEMO_TENANT_ID]);await database.query("INSERT INTO users(id,tenant_id,display_name,email,status) VALUES($1,$2,'Manager','manager@example.test','active')",[DEMO_MANAGER_ID,DEMO_TENANT_ID]);});afterEach(async()=>database.close());
it("persists encrypted push data, revokes it and atomically audits every mutation",async()=>{const context=createDevelopmentRequestContext();await database.query("SELECT set_config('app.actor_id',$1,false),set_config('app.actor_type','user',false),set_config('app.channel','web',false),set_config('app.trace_id',$2,false)",[context.actorId,context.traceId]);const device=await service.registerDevice(context,{installationId:"11000000-0000-4000-8000-000000000001",displayName:"桌面工作台",clientType:"desktop_pwa",platform:"Windows",appVersion:"0.9.0"});expect(await service.listDevices(context)).toHaveLength(1);await service.subscribe(context,device.id,{endpointDigest:"b".repeat(64),encryptedPayload:"ciphertext-only",initializationVector:"iv",authenticationTag:"tag",keyRef:"secret://client/key"});const rows=await database.query<{encrypted_payload:string;status:string}>("SELECT encrypted_payload,status FROM client_push_subscriptions");expect(rows.rows[0]).toEqual({encrypted_payload:"ciphertext-only",status:"active"});await service.revoke(context,device.id);expect((await database.query<{status:string}>("SELECT status FROM client_push_subscriptions")).rows[0].status).toBe("revoked");const audits=await database.query<{actor_id:string;trace_id:string;resource_type:string;before_digest:string|null;after_digest:string|null;metadata:Record<string,string>}>("SELECT actor_id,trace_id,resource_type,before_digest,after_digest,metadata FROM audit_events WHERE resource_type IN ('client_devices','client_push_subscriptions') ORDER BY occurred_at");expect(audits.rows.length).toBeGreaterThanOrEqual(5);expect(audits.rows.every(row=>row.actor_id===context.actorId&&row.trace_id===context.traceId&&row.metadata.source==='atomic-database-trigger')).toBe(true);expect(JSON.stringify(audits.rows)).not.toContain("ciphertext-only");});
it("enables forced RLS and atomic audit triggers on every tenant-bearing business table",async()=>{const result=await database.query<{table_name:string;row_security:boolean;force_security:boolean;policy_count:number;audit_trigger_count:number}>(`SELECT c.relname AS table_name,c.relrowsecurity AS row_security,c.relforcerowsecurity AS force_security,count(DISTINCT p.polname)::int AS policy_count,count(DISTINCT t.tgname) FILTER(WHERE t.tgname='nexus_atomic_audit')::int AS audit_trigger_count FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid AND a.attname='tenant_id' AND NOT a.attisdropped LEFT JOIN pg_policy p ON p.polrelid=c.oid LEFT JOIN pg_trigger t ON t.tgrelid=c.oid AND NOT t.tgisinternal WHERE n.nspname='public' AND c.relkind='r' GROUP BY c.relname,c.relrowsecurity,c.relforcerowsecurity ORDER BY c.relname`);expect(result.rows.length).toBeGreaterThan(50);expect(result.rows.filter(row=>!row.row_security||!row.force_security||row.policy_count<1)).toEqual([]);expect(result.rows.filter(row=>row.table_name!=="audit_events"&&row.audit_trigger_count!==1)).toEqual([]);expect(result.rows.find(row=>row.table_name==="audit_events")?.audit_trigger_count).toBe(0);const auditPolicies=await database.query<{cmd:string}>("SELECT cmd FROM pg_policies WHERE schemaname='public' AND tablename='audit_events' ORDER BY cmd");expect(auditPolicies.rows.map(row=>row.cmd)).toEqual(["INSERT","SELECT"]);});
});
