"use client";
import { BellRing, CheckCircle2, CloudOff, Download, KeyRound, Laptop, LockKeyhole, RefreshCw, ShieldCheck, Smartphone, Trash2, Wifi, WifiOff, XCircle } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { clearOfflineData, deleteOfflineDraft, listOfflineDrafts, saveOfflineDraft, type OfflineDraft } from "@/src/client/offline-draft-store";

const APP_VERSION="0.11.0";const INSTALLATION_KEY="nexus-installation-id";
type Device={id:string;installationId:string;displayName:string;clientType:string;platform:string;appVersion:string;trustLevel:string;status:string;pushEnabled:boolean;lastSeenAt:string;registeredAt:string;version:number};
type Bootstrap={policy:{minimumVersion:string;managedDeviceRequired:boolean;offlineDrafts:"disabled"|"internal";pushEnabled:boolean;pushPublicKey?:string;draftRetentionDays:number};versionSupported:boolean;device?:Device;features:{offlineDrafts:boolean;push:boolean};shortcuts:Array<{id:string;label:string;path:string}>};
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};

function installationId(){let value=localStorage.getItem(INSTALLATION_KEY);if(!value){value=crypto.randomUUID();localStorage.setItem(INSTALLATION_KEY,value);}return value;}
function clientType():"web_pwa"|"desktop_pwa"|"mobile_pwa"{const standalone=window.matchMedia("(display-mode: standalone)").matches;return standalone?(window.innerWidth<=760?"mobile_pwa":"desktop_pwa"):"web_pwa";}
function applicationServerKey(value:string){const padding="=".repeat((4-value.length%4)%4);const raw=atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from(raw,char=>char.charCodeAt(0));}

export function ClientPlatformView({onNotice}:{onNotice:(message:string)=>void}){
  const [online,setOnline]=useState(true);const [serviceWorker,setServiceWorker]=useState(false);const [installed,setInstalled]=useState(false);const [prompt,setPrompt]=useState<InstallPromptEvent>();
  const [bootstrap,setBootstrap]=useState<Bootstrap>();const [devices,setDevices]=useState<Device[]>([]);const [loading,setLoading]=useState(true);const [working,setWorking]=useState("");
  const [draftTitle,setDraftTitle]=useState("");const [draftBody,setDraftBody]=useState("");const [drafts,setDrafts]=useState<OfflineDraft[]>([]);

  const load=useCallback(async()=>{setLoading(true);try{const id=installationId();const [bootstrapResponse,devicesResponse]=await Promise.all([fetch(`/api/v1/client/bootstrap?installationId=${encodeURIComponent(id)}&appVersion=${APP_VERSION}`,{cache:"no-store"}),fetch("/api/v1/client/devices",{cache:"no-store"})]);const [bootstrapPayload,devicesPayload]=await Promise.all([bootstrapResponse.json(),devicesResponse.json()]);if(!bootstrapResponse.ok||!devicesResponse.ok)throw new Error("客户端策略读取失败");setBootstrap(bootstrapPayload.data);setDevices(devicesPayload.data);if(bootstrapPayload.data.features.offlineDrafts)setDrafts(await listOfflineDrafts());else setDrafts([]);}catch(error){onNotice(error instanceof Error?error.message:"客户端状态读取失败");}finally{setLoading(false);}},[onNotice]);
  useEffect(()=>{const initial=window.setTimeout(()=>{setOnline(navigator.onLine);setInstalled(window.matchMedia("(display-mode: standalone)").matches);setServiceWorker("serviceWorker" in navigator&&Boolean(navigator.serviceWorker.controller));void load();},0);const onlineHandler=()=>setOnline(true),offlineHandler=()=>setOnline(false),readyHandler=()=>setServiceWorker(true),promptHandler=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPromptEvent);};window.addEventListener("online",onlineHandler);window.addEventListener("offline",offlineHandler);window.addEventListener("nexus:pwa-ready",readyHandler);window.addEventListener("beforeinstallprompt",promptHandler);return()=>{window.clearTimeout(initial);window.removeEventListener("online",onlineHandler);window.removeEventListener("offline",offlineHandler);window.removeEventListener("nexus:pwa-ready",readyHandler);window.removeEventListener("beforeinstallprompt",promptHandler);};},[load]);

  async function register(){setWorking("register");try{const userAgentData=(navigator as Navigator&{userAgentData?:{platform?:string}}).userAgentData;const response=await fetch("/api/v1/client/devices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({installationId:installationId(),displayName:`${clientType()==="mobile_pwa"?"移动":"桌面"}工作台`,clientType:clientType(),platform:userAgentData?.platform||navigator.platform||"browser",appVersion:APP_VERSION})});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||"设备登记失败");onNotice("当前安装已登记，设备不会因此自动获得受管信任");await load();}catch(error){onNotice(error instanceof Error?error.message:"设备登记失败");}finally{setWorking("");}}
  async function revoke(id:string){setWorking(id);try{const response=await fetch(`/api/v1/client/devices/${id}/revoke`,{method:"POST"});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||"设备撤销失败");if(bootstrap?.device?.id===id){await clearOfflineData();localStorage.removeItem(INSTALLATION_KEY);}onNotice("设备已撤销，本地加密草稿已清除");await load();}catch(error){onNotice(error instanceof Error?error.message:"设备撤销失败");}finally{setWorking("");}}
  async function install(){if(!prompt){onNotice("请使用浏览器菜单中的“安装应用/添加到主屏幕”");return;}await prompt.prompt();const choice=await prompt.userChoice;setPrompt(undefined);if(choice.outcome==="accepted")setInstalled(true);}
  async function enablePush(){if(!bootstrap?.device||!bootstrap.policy.pushPublicKey){onNotice("推送公钥尚未由管理员配置");return;}setWorking("push");try{if(Notification.permission==="denied")throw new Error("浏览器已拒绝通知，请在站点设置中重新授权");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("未授予通知权限");const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationServerKey(bootstrap.policy.pushPublicKey)});const response=await fetch(`/api/v1/client/devices/${bootstrap.device.id}/push-subscription`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(subscription.toJSON())});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||"推送订阅失败");onNotice("已启用通用工作提醒，敏感业务内容不会进入系统通知");await load();}catch(error){onNotice(error instanceof Error?error.message:"推送订阅失败");}finally{setWorking("");}}
  async function saveDraft(){if(!draftTitle.trim()||!draftBody.trim())return;setWorking("draft");try{await saveOfflineDraft({title:draftTitle.trim(),body:draftBody.trim()});setDraftTitle("");setDraftBody("");setDrafts(await listOfflineDrafts());onNotice("草稿已使用设备不可导出密钥加密，7 天后自动清理");}catch(error){onNotice(error instanceof Error?error.message:"离线草稿保存失败");}finally{setWorking("");}}
  async function removeDraft(id:string){await deleteOfflineDraft(id);setDrafts(await listOfflineDrafts());}
  const current=bootstrap?.device;
  return <div className="client-view">
    <header className="client-hero"><div><p className="eyebrow">OWNED CLIENT PLATFORM</p><h1>设备与客户端</h1><p>用同一身份、权限和审计内核安装到桌面或移动端；客户端不复制企业事实，也不缓存业务页面。</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?"spin":""}/>刷新状态</button></header>
    <section className="client-status-ribbon">
      <div className={online?"good":"bad"}>{online?<Wifi size={18}/>:<WifiOff size={18}/>}<span><strong>{online?"在线":"离线"}</strong><small>网络状态</small></span></div>
      <div className={serviceWorker?"good":"warn"}><ShieldCheck size={18}/><span><strong>{serviceWorker?"已接管":"注册中"}</strong><small>安全离线边界</small></span></div>
      <div className={installed?"good":"neutral"}><Download size={18}/><span><strong>{installed?"已安装":"浏览器模式"}</strong><small>PWA 形态</small></span></div>
      <div className={current?.status==="active"?"good":"warn"}><KeyRound size={18}/><span><strong>{current?.status==="active"?"已登记":current?.status==="pending"?"待受管验证":"未登记"}</strong><small>当前设备</small></span></div>
    </section>
    <div className="client-grid">
      <section className="client-card device-card"><header><span><Laptop size={18}/><b>当前安装</b></span><small>v{APP_VERSION}</small></header>
        <div className="device-identity"><span className="device-glyph">{clientType()==="mobile_pwa"?<Smartphone size={24}/>:<Laptop size={24}/>}</span><div><strong>{current?.displayName||"尚未登记的浏览器"}</strong><p>{current?`${current.platform} · ${current.clientType}`:"设备 ID 只用于生命周期管理，不作为身份凭据。"}</p></div></div>
        <dl><div><dt>信任级别</dt><dd>{current?.trustLevel||"unmanaged"}</dd></div><div><dt>最低版本</dt><dd>{bootstrap?.policy.minimumVersion||"探测中"}</dd></div><div><dt>离线草稿</dt><dd>{bootstrap?.features.offlineDrafts?"允许 Internal":"禁用"}</dd></div><div><dt>系统推送</dt><dd>{bootstrap?.features.push?"可启用":"策略禁用"}</dd></div></dl>
        <div className="client-actions"><button className="client-primary" onClick={()=>void(current?install():register())} disabled={Boolean(working)}>{current?<><Download size={14}/>安装/打开应用</>:<><KeyRound size={14}/>登记当前安装</>}</button>{current&&bootstrap?.features.push?<button onClick={()=>void enablePush()} disabled={Boolean(working)}><BellRing size={14}/>启用通用提醒</button>:null}{current?<button className="client-danger" onClick={()=>void revoke(current.id)} disabled={Boolean(working)}><XCircle size={14}/>撤销设备</button>:null}</div>
      </section>
      <section className="client-card policy-card"><header><span><ShieldCheck size={18}/><b>企业设备策略</b></span><small>{bootstrap?.policy.managedDeviceRequired?"受管设备必需":"允许未受管在线访问"}</small></header>
        <ul><li><CheckCircle2 size={14}/><span><strong>API 与业务页永不离线缓存</strong><small>断网只展示不含企业数据的通用页面</small></span></li><li><CheckCircle2 size={14}/><span><strong>客户端自报不提升信任</strong><small>PWA 登记固定为 unmanaged，等待 MDM/证明适配</small></span></li><li><CheckCircle2 size={14}/><span><strong>通知只发通用提示</strong><small>人员、金额、客户和审批结果不进入锁屏通知</small></span></li><li><LockKeyhole size={14}/><span><strong>机密与受限数据禁止离线</strong><small>Internal 草稿也必须由用户明确保存</small></span></li></ul>
      </section>
    </div>
    <section className="client-card offline-drafts"><header><span><CloudOff size={18}/><b>加密离线草稿</b></span><small>{bootstrap?.features.offlineDrafts?"设备密钥 · 7 天保留":"当前策略未开放"}</small></header>
      {bootstrap?.features.offlineDrafts?<><div className="draft-compose"><input value={draftTitle} onChange={event=>setDraftTitle(event.target.value)} placeholder="草稿标题（将被加密）" maxLength={80}/><textarea value={draftBody} onChange={event=>setDraftBody(event.target.value)} placeholder="仅限 Internal 内容；恢复在线后由你检查并主动提交" rows={3} maxLength={2000}/><button onClick={()=>void saveDraft()} disabled={working==="draft"||!draftTitle.trim()||!draftBody.trim()}><LockKeyhole size={14}/>加密保存</button></div><div className="draft-list">{drafts.length?drafts.map(draft=><article key={draft.id}><div><strong>{draft.title}</strong><p>{draft.body}</p><small>创建 {new Date(draft.createdAt).toLocaleString("zh-CN")} · 到期 {new Date(draft.expiresAt).toLocaleDateString("zh-CN")}</small></div><button aria-label={`删除草稿 ${draft.title}`} onClick={()=>void removeDraft(draft.id)}><Trash2 size={14}/></button></article>):<div className="draft-empty"><LockKeyhole size={18}/><span>没有本地草稿；明文不会写入索引或 Cache Storage。</span></div>}</div></>:<div className="draft-disabled"><ShieldCheck size={19}/><div><strong>离线数据保持关闭</strong><p>管理员需显式允许 Internal 草稿，且当前设备必须 active、版本达标并满足受管策略。</p></div></div>}
    </section>
    <section className="client-card known-devices"><header><span><Smartphone size={18}/><b>我的设备</b></span><small>{devices.length} 个登记</small></header><div>{devices.length?devices.map(device=><article key={device.id}><span className={device.status==="active"?"device-dot active":"device-dot"}/><div><strong>{device.displayName}</strong><small>{device.platform} · v{device.appVersion} · {device.trustLevel}</small></div><b>{device.status}</b>{device.status!=="revoked"?<button onClick={()=>void revoke(device.id)} disabled={working===device.id}>撤销</button>:null}</article>):<p className="no-devices">尚无设备。登记只建立可撤销记录，不会授予额外业务权限。</p>}</div></section>
  </div>;
}
