import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    version: "0.11.0-enterprise-acceptance",
    modules: [
      "identity",
      "organization",
      "authorization",
      "audit",
      "events",
      "agent",
      "integration",
      "strategy",
      "delivery",
      "governance",
      "collaboration",
      "management-loop",
      "workflow",
      "knowledge",
      "meeting-governance",
      "enterprise-intelligence",
      "organization-governance",
      "talent-protection",
      "enterprise-oidc",
      "production-readiness",
      "managed-secrets",
      "operations-and-recovery",
      "client-platform",
      "secure-offline-drafts",
      "enterprise-governance",
      "organization-change-handoff",
      "project-baseline-change",
      "management-attention",
      "project-closure-gate",
      "compensating-transactions",
    ],
    providers: ["feishu", "dingtalk", "wecom"],
    connectorTransports: ["feishu-long-connection", "dingtalk-stream", "http-callback"],
    connectorSecurity: ["signature-verification", "aes-decryption", "timestamp-window", "replay-defense", "inbox-idempotency", "notification-atomic-claim", "unknown-outcome-halt", "live-acceptance-preflight", "append-only-acceptance-evidence", "hash-bound-test-delivery-confirmation"],
    agentAutonomy: ["L0", "L1", "L2", "L3"],
    agentTools: ["management.create_risk"],
    highRiskPolicy: "R3-confirmation-required; R4-disabled",
    workflowGovernance: ["version-pinning", "separation-of-duties", "parallel-any-all", "delegate", "add-approver", "withdraw", "sla-escalation"],
    meetingGovernance: ["human-confirmation", "decision-materialization", "action-materialization", "idempotent-recovery"],
    knowledgeGovernance: ["document-versioning", "classification", "pre-filter", "post-filter", "citations", "untrusted-source-handling"],
    enterpriseManagement: ["strategy-themes", "okr-kpi-separation", "metric-lineage", "portfolio", "operating-review", "raci", "capacity-planning"],
    talentProtection: ["evidence-only", "explicit-visibility", "no-scoring", "no-ranking", "no-employment-decisions", "one-to-one-excluded", "monitoring-signals-prohibited"],
    productionIdentity: ["oidc-code-flow", "pkce", "state", "nonce", "jwks-rs256", "explicit-subject-mapping", "signed-session", "grace-key-rotation"],
    productionOperations: ["fail-closed-readiness", "managed-secret-references", "structured-telemetry", "security-headers", "csrf-origin-check", "encrypted-backup", "verified-restore", "forward-migration", "container-gate"],
    clientPlatform: ["installable-pwa", "device-registration", "device-revocation", "managed-trust-gate", "encrypted-push-subscription", "generic-lock-screen-notification", "network-only-api", "generic-offline-page", "device-key-encrypted-internal-drafts"],
    enterpriseGovernance: ["authoritative-request-authorization", "objective-linked-project-initiation", "organization-change", "work-handoff", "baseline-approval", "attention-deduplication", "atomic-project-closure", "version-bound-compensation"],
  });
}
