import { randomUUID } from "node:crypto";
import type { RequestContext } from "@/src/platform/context/request-context";

export const DEMO_TENANT_ID = "00000000-0000-4000-8000-000000000001";
export const DEMO_MANAGER_ID = "10000000-0000-4000-8000-000000000001";
export const DEMO_PROJECT_ID = "30000000-0000-4000-8000-000000000001";
export const DEMO_OBJECTIVE_ID = "40000000-0000-4000-8000-000000000001";

const DEVELOPMENT_PERMISSIONS = [
  "project:read",
  "project:create",
  "objective:read",
  "objective:create",
  "risk:read",
  "task:read",
  "action_item:read",
  "risk:create",
  "decision:approve",
  "action_item:update",
  "task:update",
  "issue:create",
  "process_instance:read",
  "process_instance:create",
  "process_instance:update",
  "process_instance:approve",
  "process_definition:admin",
  "approval:approve",
  "approval:update",
  "meeting:read",
  "meeting:approve",
  "document:read",
  "document:create",
  "document:update",
  "document:admin",
  "enterprise_intelligence:read",
  "metric:update",
  "operating_review:approve",
  "responsibility:admin",
  "capacity_plan:admin",
  "talent_evidence:read",
  "platform:operations:read",
  "integration_acceptance:read",
  "integration_acceptance:execute",
  "integration_delivery:create",
  "integration_delivery:execute",
  "wecom_app:read",
  "wecom_app:admin",
  "wecom_message:send",
  "client:bootstrap:read",
  "client:device:read",
  "client:device:register",
  "client:device:revoke",
  "client:push:subscribe",
  "enterprise_governance:read",
  "organization_change:create",
  "organization_change:approve",
  "organization_change:execute",
  "project_change:update",
  "project_change:approve",
  "project_change:execute",
  "project_closure:update",
  "project_closure:approve",
  "management_attention:admin",
  "compensation:execute",
  "agent_job:reconcile",
  "management_intelligence:read",
  "management_cadence:create",
  "management_cadence:update",
  "cadence_occurrence:update",
  "cadence_occurrence:approve",
  "metric_semantic_profile:admin",
  "metric_quality:update",
  "portfolio_scenario:create",
  "portfolio_scenario:approve",
  "enterprise_case:create",
  "enterprise_case:update",
  "enterprise_case:approve",
  "ai_governance_evaluation:create",
  "ai_governance:read",
  "management_channel_action:create",
  "work_task:read",
  "work_task:create",
  "work_task:assign",
  "work_task:assign_department",
  "work_task:claim",
  "work_task:update",
  "work_task:handoff",
  "work_task:handoff_cross_department",
  "work_task:accept_handoff",
  "work_task:admin",
  "message_pool:read",
  "message_pool:publish",
  "message_pool:moderate",
  "memory:read",
  "memory:write",
  "memory:read_shared",
  "memory:share",
  "memory:manage",
  "pi:session:create",
  "pi:session:read",
  "pi:session:write",
  "pi:session:branch",
  "pi:workspace:read",
  "pi:workspace:write",
  "pi:sandbox:execute",
  "pi:mcp:use",
  "pi:catalog:read",
  "pi:approval:create",
  "pi:approval:read",
  "pi:approval:decide:r2",
  "pi:approval:decide:r3",
  "pi:approval:resume",
  "pi:approval:cancel",
  "pi:delegation:create",
  "pi:delegation:cancel",
  "pi:mcp:admin",
  "pi:mcp:bind",
  "pi:registry:read",
  "pi:registry:write",
  "pi:registry:approve",
  "pi:registry:scan",
  "pi:profile:admin",
  "pi:quota:read",
  "pi:quota:admin",
  "pi:audit:read",
  "pi:audit:write",
  "pi:telemetry:write",
  "pi:evaluation:write",
  "pi:model:read",
  "pi:model:admin",
  "pi:model:usage",
  "pi:model:cancel",
  "pi:usage:read",
  "pi:kill-switch:read",
  "pi:kill-switch:write",
  "pi:kill-switch:global",
  "pi:security:read",
  "pi:capacity:read",
  "pi:capacity:admin",
  "pi:capacity:write",
  "pi:failure:inject",
  "pi:recovery:read",
  "pi:recovery:write",
  "pi:preproduction:read",
  "pi:secret:lease",
  "pi:secret:revoke",
  "pi:pilot:read",
  "pi:pilot:manage",
  "pi:pilot:exit",
  "pi:release:read",
  "pi:release:manage",
  "pi:release:approve",
  "pi:release:rollout",
  "pi:release:revoke",
  "pi:change:read",
  "pi:change:submit",
  "pi:change:merge",
  "pi:change:release",
  "pi:change:execute",
  "pi:change:admin",
  "pi:data:confidential",
  "pi:data:restricted",
  "pi:release:propose",
];

export function createDevelopmentRequestContext(traceId: string = randomUUID()): RequestContext {
  return {
    tenantId: DEMO_TENANT_ID,
    actorId: DEMO_MANAGER_ID,
    sessionId: "development-session",
    channel: "web",
    traceId,
    roles: ["enterprise_manager"],
    permissions: [...DEVELOPMENT_PERMISSIONS],
    dataScopes: [{ type: "tenant" }],
  };
}
