import type { RequestContext } from "@/src/platform/context/request-context";
import type { DatabaseExecutor, TransactionalDatabase } from "@/src/platform/database/executor";
import type { PiModelRoute, PiModelRouteStore, PiModelUsageRecord } from "@/src/modules/pi-agent/domain/model-contracts";
import type { PiEvaluationResult, PiObservabilityStore, PiRegressionAlert, PiTelemetryMetric, PiTraceRecord } from "@/src/modules/pi-agent/domain/observability-contracts";
import type { PiQuotaPolicy, PiQuotaReservation, PiQuotaStore, PiQuotaUsage } from "@/src/modules/pi-agent/domain/quota-contracts";

type Row = Record<string, unknown>;
function clone<T>(value: T): T { return structuredClone(value); }
function text(value: unknown): string { return value instanceof Date ? value.toISOString() : String(value); }
function optionalText(value: unknown): string | undefined { return value === null || value === undefined ? undefined : text(value); }
function array<T>(value: unknown): T[] { if (Array.isArray(value)) return value as T[]; if (typeof value === "string") { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed as T[] : []; } catch { return []; } } return []; }
function object(value: unknown): Record<string, unknown> { if (value && typeof value === "object" && !Array.isArray(value)) return value as Record<string, unknown>; if (typeof value === "string") { try { const parsed = JSON.parse(value); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {}; } catch { return {}; } } return {}; }
function iso(value: unknown): string { return new Date(String(value)).toISOString(); }
function routeFromRow(row: Row): PiModelRoute { return { id: text(row.id), tenantId: text(row.tenant_id), routeId: text(row.route_id), version: text(row.version), provider: text(row.provider), model: text(row.model), region: text(row.region), egress: row.egress as PiModelRoute["egress"], allowedDataClassifications: array<PiModelRoute["allowedDataClassifications"][number]>(row.allowed_data_classifications), fallbackRouteIds: array<string>(row.fallback_route_ids), maxInputTokens: Number(row.max_input_tokens), maxOutputTokens: Number(row.max_output_tokens), inputCostMicrosPerMillion: Number(row.input_cost_micros_per_million), outputCostMicrosPerMillion: Number(row.output_cost_micros_per_million), status: row.status as PiModelRoute["status"], createdAt: iso(row.created_at), ...(row.approved_at ? { approvedAt: iso(row.approved_at) } : {}), ...(row.revoked_at ? { revokedAt: iso(row.revoked_at) } : {}) }; }
function usageFromRow(row: Row): PiModelUsageRecord { return { usageId: text(row.usage_id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), routeId: text(row.route_id), provider: text(row.provider), model: text(row.model), dataClassification: row.data_classification as PiModelUsageRecord["dataClassification"], inputTokens: Number(row.input_tokens), outputTokens: Number(row.output_tokens), latencyMs: Number(row.latency_ms), status: row.status as PiModelUsageRecord["status"], idempotencyKey: text(row.idempotency_key), costMicros: Number(row.cost_micros), traceId: text(row.trace_id), ...(optionalText(row.workspace_id) ? { workspaceId: text(row.workspace_id) } : {}), ...(optionalText(row.session_id) ? { sessionId: text(row.session_id) } : {}), ...(optionalText(row.run_id) ? { runId: text(row.run_id) } : {}), createdAt: iso(row.created_at) }; }
function traceFromRow(row: Row): PiTraceRecord { return { id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), traceId: text(row.trace_id), ...(optionalText(row.workspace_id) ? { workspaceId: text(row.workspace_id) } : {}), ...(optionalText(row.session_id) ? { sessionId: text(row.session_id) } : {}), ...(optionalText(row.run_id) ? { runId: text(row.run_id) } : {}), ...(optionalText(row.sandbox_run_id) ? { sandboxRunId: text(row.sandbox_run_id) } : {}), ...(optionalText(row.tool_call_id) ? { toolCallId: text(row.tool_call_id) } : {}), ...(optionalText(row.model_route_id) ? { modelRouteId: text(row.model_route_id) } : {}), skillDigests: array<string>(row.skill_digests), ...(optionalText(row.git_commit_sha) ? { gitCommitSha: text(row.git_commit_sha) } : {}), dataClassification: row.data_classification as PiTraceRecord["dataClassification"], status: row.status as PiTraceRecord["status"], ...(optionalText(row.input_digest) ? { inputDigest: text(row.input_digest) } : {}), ...(optionalText(row.output_digest) ? { outputDigest: text(row.output_digest) } : {}), ...(row.duration_ms !== null && row.duration_ms !== undefined ? { durationMs: Number(row.duration_ms) } : {}), ...(optionalText(row.error_code) ? { errorCode: text(row.error_code) } : {}), startedAt: iso(row.started_at), ...(row.ended_at ? { endedAt: iso(row.ended_at) } : {}) }; }
function metricFromRow(row: Row): PiTelemetryMetric { return { id: text(row.id), tenantId: text(row.tenant_id), traceId: text(row.trace_id), name: text(row.name), value: Number(row.value), unit: row.unit as PiTelemetryMetric["unit"], dimensions: object(row.dimensions) as Record<string, string>, createdAt: iso(row.created_at) }; }
function evaluationFromRow(row: Row): PiEvaluationResult { return { id: text(row.id), tenantId: text(row.tenant_id), suiteId: text(row.suite_id), caseId: text(row.case_id), ...(optionalText(row.route_id) ? { routeId: text(row.route_id) } : {}), ...(optionalText(row.trace_id) ? { traceId: text(row.trace_id) } : {}), status: row.status as PiEvaluationResult["status"], score: Number(row.score), threshold: Number(row.threshold), metricSummary: Object.fromEntries(Object.entries(object(row.metric_summary)).map(([key, value]) => [key, Number(value)])), ...(optionalText(row.output_digest) ? { outputDigest: text(row.output_digest) } : {}), correctionRequired: Boolean(row.correction_required), createdAt: iso(row.created_at) }; }
function alertFromRow(row: Row): PiRegressionAlert { return { id: text(row.id), tenantId: text(row.tenant_id), suiteId: text(row.suite_id), metric: text(row.metric), baseline: Number(row.baseline), observed: Number(row.observed), threshold: Number(row.threshold), severity: row.severity as PiRegressionAlert["severity"], status: row.status as PiRegressionAlert["status"], createdAt: iso(row.created_at) }; }
function policyFromRow(row: Row): PiQuotaPolicy { return { id: text(row.id), tenantId: text(row.tenant_id), scope: row.scope as PiQuotaPolicy["scope"], ...(optionalText(row.scope_id) ? { scopeId: text(row.scope_id) } : {}), version: Number(row.version), maxConcurrentRuns: Number(row.max_concurrent_runs), maxTokens: Number(row.max_tokens), maxCostMicros: Number(row.max_cost_micros), maxStorageBytes: Number(row.max_storage_bytes), maxToolCalls: Number(row.max_tool_calls), status: row.status as PiQuotaPolicy["status"], createdAt: iso(row.created_at) }; }
function reservationFromRow(row: Row): PiQuotaReservation { return { id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), ...(optionalText(row.run_id) ? { runId: text(row.run_id) } : {}), scope: row.scope as PiQuotaReservation["scope"], ...(optionalText(row.scope_id) ? { scopeId: text(row.scope_id) } : {}), policyId: text(row.policy_id), policyVersion: Number(row.policy_version), idempotencyKey: text(row.idempotency_key), reserved: object(row.reserved) as unknown as PiQuotaUsage, consumed: object(row.consumed) as unknown as PiQuotaUsage, status: row.status as PiQuotaReservation["status"], createdAt: iso(row.created_at), ...(row.released_at ? { releasedAt: iso(row.released_at) } : {}) }; }

export class InMemoryPiModelRouteStore implements PiModelRouteStore {
  private readonly routes = new Map<string, PiModelRoute>();
  private readonly usage = new Map<string, PiModelUsageRecord>();
  private key(tenantId: string, routeId: string, version: string): string { return `${tenantId}:${routeId}:${version}`; }
  async putRoute(route: PiModelRoute): Promise<void> { const key = this.key(route.tenantId, route.routeId, route.version); if (this.routes.has(key)) throw new Error("PI_MODEL_ROUTE_DUPLICATE"); this.routes.set(key, clone(route)); }
  async getRoute(context: RequestContext, routeId: string, version?: string): Promise<PiModelRoute | null> { const items = [...this.routes.values()].filter((route) => route.tenantId === context.tenantId && route.routeId === routeId && (!version || route.version === version)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return items[0] ? clone(items[0]) : null; }
  async listRoutes(context: RequestContext): Promise<PiModelRoute[]> { return [...this.routes.values()].filter((route) => route.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async updateRoute(context: RequestContext, routeId: string, version: string, patch: Partial<Pick<PiModelRoute, "status" | "approvedAt" | "revokedAt">>): Promise<PiModelRoute> { const key = this.key(context.tenantId, routeId, version); const current = this.routes.get(key); if (!current) throw new Error("PI_MODEL_ROUTE_NOT_FOUND"); const updated = { ...current, ...patch }; this.routes.set(key, clone(updated)); return clone(updated); }
  async appendUsage(record: PiModelUsageRecord): Promise<{ record: PiModelUsageRecord; created: boolean }> { const existing = [...this.usage.values()].find((item) => item.tenantId === record.tenantId && item.idempotencyKey === record.idempotencyKey); if (existing) return { record: clone(existing), created: false }; this.usage.set(`${record.tenantId}:${record.usageId}`, clone(record)); return { record: clone(record), created: true }; }
  async listUsage(context: RequestContext, limit = 100): Promise<PiModelUsageRecord[]> { return [...this.usage.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map(clone); }
}

export class InMemoryPiObservabilityStore implements PiObservabilityStore {
  private readonly traces = new Map<string, PiTraceRecord>();
  private readonly metrics = new Map<string, PiTelemetryMetric>();
  private readonly evaluations = new Map<string, PiEvaluationResult>();
  private readonly alerts = new Map<string, PiRegressionAlert>();
  async appendTrace(trace: PiTraceRecord): Promise<void> { this.traces.set(`${trace.tenantId}:${trace.id}`, clone(trace)); }
  async appendMetric(metric: PiTelemetryMetric): Promise<void> { this.metrics.set(`${metric.tenantId}:${metric.id}`, clone(metric)); }
  async appendEvaluation(result: PiEvaluationResult): Promise<void> { this.evaluations.set(`${result.tenantId}:${result.id}`, clone(result)); }
  async appendAlert(alert: PiRegressionAlert): Promise<void> { this.alerts.set(`${alert.tenantId}:${alert.id}`, clone(alert)); }
  async listTraces(context: RequestContext, limit = 100): Promise<PiTraceRecord[]> { return [...this.traces.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.startedAt.localeCompare(a.startedAt)).slice(0, limit).map(clone); }
  async listMetrics(context: RequestContext, limit = 100): Promise<PiTelemetryMetric[]> { return [...this.metrics.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map(clone); }
  async listEvaluations(context: RequestContext, limit = 100): Promise<PiEvaluationResult[]> { return [...this.evaluations.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map(clone); }
  async listAlerts(context: RequestContext, limit = 100): Promise<PiRegressionAlert[]> { return [...this.alerts.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map(clone); }
}

export class InMemoryPiQuotaStore implements PiQuotaStore {
  private readonly policies = new Map<string, PiQuotaPolicy>();
  private readonly reservations = new Map<string, PiQuotaReservation>();
  async putPolicy(policy: PiQuotaPolicy): Promise<void> { const key = `${policy.tenantId}:${policy.id}`; if (this.policies.has(key)) throw new Error("PI_QUOTA_POLICY_DUPLICATE"); this.policies.set(key, clone(policy)); }
  async listPolicies(context: RequestContext): Promise<PiQuotaPolicy[]> { return [...this.policies.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async getPolicy(context: RequestContext, policyId: string): Promise<PiQuotaPolicy | null> { const item = this.policies.get(`${context.tenantId}:${policyId}`); return item ? clone(item) : null; }
  async getReservationByIdempotency(context: RequestContext, idempotencyKey: string): Promise<PiQuotaReservation | null> { const item = [...this.reservations.values()].find((candidate) => candidate.tenantId === context.tenantId && candidate.idempotencyKey === idempotencyKey); return item ? clone(item) : null; }
  async getReservation(context: RequestContext, reservationId: string): Promise<PiQuotaReservation | null> { const item = this.reservations.get(`${context.tenantId}:${reservationId}`); return item ? clone(item) : null; }
  async createReservation(reservation: PiQuotaReservation): Promise<{ reservation: PiQuotaReservation; created: boolean }> { const existing = [...this.reservations.values()].find((candidate) => candidate.tenantId === reservation.tenantId && candidate.idempotencyKey === reservation.idempotencyKey); if (existing) return { reservation: clone(existing), created: false }; this.reservations.set(`${reservation.tenantId}:${reservation.id}`, clone(reservation)); return { reservation: clone(reservation), created: true }; }
  async updateReservation(context: RequestContext, reservationId: string, patch: Partial<Pick<PiQuotaReservation, "consumed" | "status" | "releasedAt">>): Promise<PiQuotaReservation> { const key = `${context.tenantId}:${reservationId}`; const current = this.reservations.get(key); if (!current) throw new Error("PI_QUOTA_RESERVATION_NOT_FOUND"); const updated = { ...current, ...patch }; this.reservations.set(key, clone(updated)); return clone(updated); }
  async summarize(context: RequestContext, policy: PiQuotaPolicy): Promise<PiQuotaUsage> { const values = [...this.reservations.values()].filter((item) => item.tenantId === context.tenantId && item.policyId === policy.id && item.status === "active"); return values.reduce((total, item) => ({ concurrentRuns: total.concurrentRuns + item.reserved.concurrentRuns, tokens: total.tokens + item.reserved.tokens, costMicros: total.costMicros + item.reserved.costMicros, storageBytes: total.storageBytes + item.reserved.storageBytes, toolCalls: total.toolCalls + item.reserved.toolCalls }), { concurrentRuns: 0, tokens: 0, costMicros: 0, storageBytes: 0, toolCalls: 0 }); }
}

export class PostgresPiM30Store implements PiModelRouteStore, PiObservabilityStore, PiQuotaStore {
  constructor(private readonly database: TransactionalDatabase) {}
  private scoped<T>(context: RequestContext, work: (db: DatabaseExecutor) => Promise<T>): Promise<T> { return this.database.withTenant(context.tenantId, work); }
  private systemContext(tenantId: string, traceId: string): RequestContext { return { tenantId, actorId: "00000000-0000-4000-8000-000000000000", sessionId: "system", channel: "system", traceId, roles: ["system"], permissions: [], dataScopes: [{ type: "tenant" }] }; }
  async putRoute(route: PiModelRoute): Promise<void> { await this.scoped(this.systemContext(route.tenantId, route.id), async (db) => { await db.query("INSERT INTO pi_model_routes(id,tenant_id,route_id,version,provider,model,region,egress,allowed_data_classifications,fallback_route_ids,max_input_tokens,max_output_tokens,input_cost_micros_per_million,output_cost_micros_per_million,status,created_at,approved_at,revoked_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)", [route.id, route.tenantId, route.routeId, route.version, route.provider, route.model, route.region, route.egress, route.allowedDataClassifications, route.fallbackRouteIds, route.maxInputTokens, route.maxOutputTokens, route.inputCostMicrosPerMillion, route.outputCostMicrosPerMillion, route.status, new Date(route.createdAt), route.approvedAt ? new Date(route.approvedAt) : null, route.revokedAt ? new Date(route.revokedAt) : null]); }); }
  async getRoute(context: RequestContext, routeId: string, version?: string): Promise<PiModelRoute | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_model_routes WHERE tenant_id=$1 AND route_id=$2 AND ($3::text IS NULL OR version=$3) ORDER BY created_at DESC LIMIT 1", [context.tenantId, routeId, version ?? null]); return rows[0] ? routeFromRow(rows[0]) : null; }); }
  async listRoutes(context: RequestContext): Promise<PiModelRoute[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_model_routes WHERE tenant_id=$1 ORDER BY created_at DESC", [context.tenantId])).map(routeFromRow)); }
  async updateRoute(context: RequestContext, routeId: string, version: string, patch: Partial<Pick<PiModelRoute, "status" | "approvedAt" | "revokedAt">>): Promise<PiModelRoute> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("UPDATE pi_model_routes SET status=COALESCE($4,status),approved_at=COALESCE($5,approved_at),revoked_at=COALESCE($6,revoked_at) WHERE tenant_id=$1 AND route_id=$2 AND version=$3 RETURNING *", [context.tenantId, routeId, version, patch.status ?? null, patch.approvedAt ? new Date(patch.approvedAt) : null, patch.revokedAt ? new Date(patch.revokedAt) : null]); if (!rows[0]) throw new Error("PI_MODEL_ROUTE_NOT_FOUND"); return routeFromRow(rows[0]); }); }
  async appendUsage(record: PiModelUsageRecord): Promise<{ record: PiModelUsageRecord; created: boolean }> { return this.scoped(this.systemContext(record.tenantId, record.traceId), async (db) => { const rows = await db.query<Row>("INSERT INTO pi_model_usage(usage_id,tenant_id,actor_id,workspace_id,session_id,run_id,route_id,provider,model,data_classification,input_tokens,output_tokens,latency_ms,status,idempotency_key,cost_micros,trace_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT(tenant_id,idempotency_key) DO NOTHING RETURNING *", [record.usageId, record.tenantId, record.actorId, record.workspaceId ?? null, record.sessionId ?? null, record.runId ?? null, record.routeId, record.provider, record.model, record.dataClassification, record.inputTokens, record.outputTokens, record.latencyMs, record.status, record.idempotencyKey, record.costMicros, record.traceId, new Date(record.createdAt)]); if (rows[0]) return { record: usageFromRow(rows[0]), created: true }; const existing = await db.query<Row>("SELECT * FROM pi_model_usage WHERE tenant_id=$1 AND idempotency_key=$2", [record.tenantId, record.idempotencyKey]); if (!existing[0]) throw new Error("PI_MODEL_USAGE_CONFLICT"); return { record: usageFromRow(existing[0]), created: false }; }); }
  async listUsage(context: RequestContext, limit = 100): Promise<PiModelUsageRecord[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_model_usage WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", [context.tenantId, limit])).map(usageFromRow)); }
  async appendTrace(trace: PiTraceRecord): Promise<void> { await this.scoped(this.systemContext(trace.tenantId, trace.traceId), async (db) => { await db.query("INSERT INTO pi_traces(id,tenant_id,actor_id,trace_id,workspace_id,session_id,run_id,sandbox_run_id,tool_call_id,model_route_id,skill_digests,git_commit_sha,data_classification,status,input_digest,output_digest,duration_ms,error_code,started_at,ended_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,output_digest=COALESCE(EXCLUDED.output_digest,pi_traces.output_digest),duration_ms=COALESCE(EXCLUDED.duration_ms,pi_traces.duration_ms),error_code=COALESCE(EXCLUDED.error_code,pi_traces.error_code),ended_at=COALESCE(EXCLUDED.ended_at,pi_traces.ended_at)", [trace.id, trace.tenantId, trace.actorId, trace.traceId, trace.workspaceId ?? null, trace.sessionId ?? null, trace.runId ?? null, trace.sandboxRunId ?? null, trace.toolCallId ?? null, trace.modelRouteId ?? null, trace.skillDigests, trace.gitCommitSha ?? null, trace.dataClassification, trace.status, trace.inputDigest ?? null, trace.outputDigest ?? null, trace.durationMs ?? null, trace.errorCode ?? null, new Date(trace.startedAt), trace.endedAt ? new Date(trace.endedAt) : null]); }); }
  async appendMetric(metric: PiTelemetryMetric): Promise<void> { await this.scoped(this.systemContext(metric.tenantId, metric.traceId), async (db) => { await db.query("INSERT INTO pi_telemetry_metrics(id,tenant_id,trace_id,name,value,unit,dimensions,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [metric.id, metric.tenantId, metric.traceId, metric.name, metric.value, metric.unit, metric.dimensions, new Date(metric.createdAt)]); }); }
  async appendEvaluation(result: PiEvaluationResult): Promise<void> { await this.scoped(this.systemContext(result.tenantId, result.traceId ?? result.id), async (db) => { await db.query("INSERT INTO pi_evaluation_results(id,tenant_id,suite_id,case_id,route_id,trace_id,status,score,threshold,metric_summary,output_digest,correction_required,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)", [result.id, result.tenantId, result.suiteId, result.caseId, result.routeId ?? null, result.traceId ?? null, result.status, result.score, result.threshold, result.metricSummary, result.outputDigest ?? null, result.correctionRequired, new Date(result.createdAt)]); }); }
  async appendAlert(alert: PiRegressionAlert): Promise<void> { await this.scoped(this.systemContext(alert.tenantId, alert.id), async (db) => { await db.query("INSERT INTO pi_regression_alerts(id,tenant_id,suite_id,metric,baseline,observed,threshold,severity,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)", [alert.id, alert.tenantId, alert.suiteId, alert.metric, alert.baseline, alert.observed, alert.threshold, alert.severity, alert.status, new Date(alert.createdAt)]); }); }
  async listTraces(context: RequestContext, limit = 100): Promise<PiTraceRecord[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_traces WHERE tenant_id=$1 ORDER BY started_at DESC LIMIT $2", [context.tenantId, limit])).map(traceFromRow)); }
  async listMetrics(context: RequestContext, limit = 100): Promise<PiTelemetryMetric[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_telemetry_metrics WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", [context.tenantId, limit])).map(metricFromRow)); }
  async listEvaluations(context: RequestContext, limit = 100): Promise<PiEvaluationResult[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_evaluation_results WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", [context.tenantId, limit])).map(evaluationFromRow)); }
  async listAlerts(context: RequestContext, limit = 100): Promise<PiRegressionAlert[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_regression_alerts WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", [context.tenantId, limit])).map(alertFromRow)); }
  async putPolicy(policy: PiQuotaPolicy): Promise<void> { await this.scoped(this.systemContext(policy.tenantId, policy.id), async (db) => { await db.query("INSERT INTO pi_quota_policies(id,tenant_id,scope,scope_id,version,max_concurrent_runs,max_tokens,max_cost_micros,max_storage_bytes,max_tool_calls,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)", [policy.id, policy.tenantId, policy.scope, policy.scopeId ?? null, policy.version, policy.maxConcurrentRuns, policy.maxTokens, policy.maxCostMicros, policy.maxStorageBytes, policy.maxToolCalls, policy.status, new Date(policy.createdAt)]); }); }
  async listPolicies(context: RequestContext): Promise<PiQuotaPolicy[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_quota_policies WHERE tenant_id=$1 ORDER BY created_at DESC", [context.tenantId])).map(policyFromRow)); }
  async getPolicy(context: RequestContext, policyId: string): Promise<PiQuotaPolicy | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_quota_policies WHERE tenant_id=$1 AND id=$2", [context.tenantId, policyId]); return rows[0] ? policyFromRow(rows[0]) : null; }); }
  async getReservationByIdempotency(context: RequestContext, idempotencyKey: string): Promise<PiQuotaReservation | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_quota_reservations WHERE tenant_id=$1 AND idempotency_key=$2", [context.tenantId, idempotencyKey]); return rows[0] ? reservationFromRow(rows[0]) : null; }); }
  async getReservation(context: RequestContext, reservationId: string): Promise<PiQuotaReservation | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_quota_reservations WHERE tenant_id=$1 AND id=$2", [context.tenantId, reservationId]); return rows[0] ? reservationFromRow(rows[0]) : null; }); }
  async createReservation(reservation: PiQuotaReservation): Promise<{ reservation: PiQuotaReservation; created: boolean }> { return this.scoped(this.systemContext(reservation.tenantId, reservation.id), async (db) => { const rows = await db.query<Row>("INSERT INTO pi_quota_reservations(id,tenant_id,actor_id,run_id,scope,scope_id,policy_id,policy_version,idempotency_key,reserved,consumed,status,created_at,released_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(tenant_id,idempotency_key) DO NOTHING RETURNING *", [reservation.id, reservation.tenantId, reservation.actorId, reservation.runId ?? null, reservation.scope, reservation.scopeId ?? null, reservation.policyId, reservation.policyVersion, reservation.idempotencyKey, reservation.reserved, reservation.consumed, reservation.status, new Date(reservation.createdAt), null]); if (rows[0]) return { reservation: reservationFromRow(rows[0]), created: true }; const existing = await db.query<Row>("SELECT * FROM pi_quota_reservations WHERE tenant_id=$1 AND idempotency_key=$2", [reservation.tenantId, reservation.idempotencyKey]); if (!existing[0]) throw new Error("PI_QUOTA_RESERVATION_CONFLICT"); return { reservation: reservationFromRow(existing[0]), created: false }; }); }
  async updateReservation(context: RequestContext, reservationId: string, patch: Partial<Pick<PiQuotaReservation, "consumed" | "status" | "releasedAt">>): Promise<PiQuotaReservation> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("UPDATE pi_quota_reservations SET consumed=COALESCE($3,consumed),status=COALESCE($4,status),released_at=COALESCE($5,released_at) WHERE tenant_id=$1 AND id=$2 RETURNING *", [context.tenantId, reservationId, patch.consumed ?? null, patch.status ?? null, patch.releasedAt ? new Date(patch.releasedAt) : null]); if (!rows[0]) throw new Error("PI_QUOTA_RESERVATION_NOT_FOUND"); return reservationFromRow(rows[0]); }); }
  async summarize(context: RequestContext, policy: PiQuotaPolicy): Promise<PiQuotaUsage> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT COALESCE(sum((reserved->>'concurrentRuns')::bigint),0)::bigint AS concurrent_runs, COALESCE(sum((reserved->>'tokens')::bigint),0)::bigint AS tokens, COALESCE(sum((reserved->>'costMicros')::bigint),0)::bigint AS cost_micros, COALESCE(sum((reserved->>'storageBytes')::bigint),0)::bigint AS storage_bytes, COALESCE(sum((reserved->>'toolCalls')::bigint),0)::bigint AS tool_calls FROM pi_quota_reservations WHERE tenant_id=$1 AND policy_id=$2 AND status='active'", [context.tenantId, policy.id]); const row = rows[0] ?? {}; return { concurrentRuns: Number(row.concurrent_runs ?? 0), tokens: Number(row.tokens ?? 0), costMicros: Number(row.cost_micros ?? 0), storageBytes: Number(row.storage_bytes ?? 0), toolCalls: Number(row.tool_calls ?? 0) }; }); }
}
