import type { RequestContext } from "@/src/platform/context/request-context";
import type { DatabaseExecutor, TransactionalDatabase } from "@/src/platform/database/executor";
import type {
  PiPilot,
  PiPilotDataSample,
  PiPilotEvent,
  PiPilotIncident,
  PiPilotJourney,
  PiPilotObservation,
  PiPilotParticipant,
  PiPilotReadiness,
  PiPilotStore,
} from "@/src/modules/pi-agent/domain/pilot-contracts";

type Row = Record<string, unknown>;
const clone = <T>(value: T): T => structuredClone(value);
const text = (value: unknown): string => value instanceof Date ? value.toISOString() : String(value);
const optionalText = (value: unknown): string | undefined => value === null || value === undefined ? undefined : text(value);
const iso = (value: unknown): string => new Date(String(value)).toISOString();
const jsonValue = <T>(value: unknown): T => typeof value === "string" ? JSON.parse(value) as T : value as T;

function pilotFromRow(row: Row): PiPilot {
  return { id: text(row.id), tenantId: text(row.tenant_id), createdBy: text(row.created_by), projectId: text(row.project_id), name: text(row.name), version: text(row.version), startsAt: iso(row.starts_at), endsAt: iso(row.ends_at), exitPolicyDigest: text(row.exit_policy_digest), actionDigest: text(row.action_digest), status: row.status as PiPilot["status"], createdAt: iso(row.created_at), ...(row.exited_at ? { exitedAt: iso(row.exited_at) } : {}) };
}
function participantFromRow(row: Row): PiPilotParticipant {
  return { id: text(row.id), tenantId: text(row.tenant_id), pilotId: text(row.pilot_id), subjectDigest: text(row.subject_digest), role: text(row.role), projectScopeDigest: text(row.project_scope_digest), status: row.status as PiPilotParticipant["status"], createdAt: iso(row.created_at), ...(row.revoked_at ? { revokedAt: iso(row.revoked_at) } : {}) };
}
function journeyFromRow(row: Row): PiPilotJourney {
  return { id: text(row.id), tenantId: text(row.tenant_id), pilotId: text(row.pilot_id), kind: row.kind as PiPilotJourney["kind"], sampleDigest: text(row.sample_digest), status: row.status as PiPilotJourney["status"], ...(optionalText(row.evidence_digest) ? { evidenceDigest: text(row.evidence_digest) } : {}), ...(optionalText(row.run_digest) ? { runDigest: text(row.run_digest) } : {}), ...(optionalText(row.artifact_digest) ? { artifactDigest: text(row.artifact_digest) } : {}), ...(row.quality_score === null || row.quality_score === undefined ? {} : { qualityScore: Number(row.quality_score) }), createdAt: iso(row.created_at) };
}
function observationFromRow(row: Row): PiPilotObservation {
  return { id: text(row.id), tenantId: text(row.tenant_id), pilotId: text(row.pilot_id), metric: row.metric as PiPilotObservation["metric"], windowStart: iso(row.window_start), windowEnd: iso(row.window_end), value: Number(row.value), threshold: Number(row.threshold), unit: text(row.unit), status: row.status as PiPilotObservation["status"], ...(optionalText(row.evidence_digest) ? { evidenceDigest: text(row.evidence_digest) } : {}), createdAt: iso(row.created_at) };
}
function dataSampleFromRow(row: Row): PiPilotDataSample {
  return { id: text(row.id), tenantId: text(row.tenant_id), pilotId: text(row.pilot_id), classification: row.classification as PiPilotDataSample["classification"], sampleDigest: text(row.sample_digest), status: row.status as PiPilotDataSample["status"], ...(optionalText(row.evidence_digest) ? { evidenceDigest: text(row.evidence_digest) } : {}), createdAt: iso(row.created_at) };
}
function incidentFromRow(row: Row): PiPilotIncident {
  return { id: text(row.id), tenantId: text(row.tenant_id), pilotId: text(row.pilot_id), severity: row.severity as PiPilotIncident["severity"], status: row.status as PiPilotIncident["status"], summaryDigest: text(row.summary_digest), openedAt: iso(row.opened_at), ...(row.resolved_at ? { resolvedAt: iso(row.resolved_at) } : {}) };
}
function readinessFromRow(row: Row): PiPilotReadiness {
  return { id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), pilotId: text(row.pilot_id), ready: Boolean(row.ready), checks: jsonValue<PiPilotReadiness["checks"]>(row.checks), policyVersion: Number(row.policy_version), generatedAt: iso(row.generated_at), ...(optionalText(row.failure_digest) ? { failureDigest: text(row.failure_digest) } : {}) };
}
function eventFromRow(row: Row): PiPilotEvent { return { id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), pilotId: text(row.pilot_id), kind: row.kind as PiPilotEvent["kind"], subjectDigest: text(row.subject_digest), traceId: text(row.trace_id), createdAt: iso(row.created_at) }; }

export class InMemoryPiPilotStore implements PiPilotStore {
  private readonly pilots = new Map<string, PiPilot>();
  private readonly participants = new Map<string, PiPilotParticipant>();
  private readonly journeys = new Map<string, PiPilotJourney>();
  private readonly observations = new Map<string, PiPilotObservation>();
  private readonly dataSamples = new Map<string, PiPilotDataSample>();
  private readonly incidents = new Map<string, PiPilotIncident>();
  private readonly readiness = new Map<string, PiPilotReadiness>();
  private readonly events = new Map<string, PiPilotEvent>();

  async putPilot(pilot: PiPilot): Promise<{ pilot: PiPilot; created: boolean }> { const existing = [...this.pilots.values()].find((item) => item.tenantId === pilot.tenantId && item.actionDigest === pilot.actionDigest); if (existing) return { pilot: clone(existing), created: false }; this.pilots.set(`${pilot.tenantId}:${pilot.id}`, clone(pilot)); return { pilot: clone(pilot), created: true }; }
  async findPilot(context: RequestContext, id: string): Promise<PiPilot | null> { const item = this.pilots.get(`${context.tenantId}:${id}`); return item ? clone(item) : null; }
  async findPilotByActionDigest(context: RequestContext, actionDigest: string): Promise<PiPilot | null> { const item = [...this.pilots.values()].find((candidate) => candidate.tenantId === context.tenantId && candidate.actionDigest === actionDigest); return item ? clone(item) : null; }
  async listPilots(context: RequestContext): Promise<PiPilot[]> { return [...this.pilots.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async putParticipant(participant: PiPilotParticipant): Promise<void> { this.participants.set(`${participant.tenantId}:${participant.id}`, clone(participant)); }
  async findParticipant(context: RequestContext, pilotId: string, participantId: string): Promise<PiPilotParticipant | null> { const item = this.participants.get(`${context.tenantId}:${participantId}`); return item?.pilotId === pilotId ? clone(item) : null; }
  async listParticipants(context: RequestContext, pilotId?: string): Promise<PiPilotParticipant[]> { return [...this.participants.values()].filter((item) => item.tenantId === context.tenantId && (!pilotId || item.pilotId === pilotId)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async revokeParticipant(context: RequestContext, pilotId: string, participantId: string, revokedAt: string): Promise<PiPilotParticipant> { const item = await this.findParticipant(context, pilotId, participantId); if (!item) throw new Error("PI_PILOT_PARTICIPANT_NOT_FOUND"); if (item.status === "revoked") return item; const updated = { ...item, status: "revoked" as const, revokedAt }; this.participants.set(`${context.tenantId}:${participantId}`, updated); return clone(updated); }
  async exitPilot(context: RequestContext, pilotId: string, exitedAt: string): Promise<PiPilot> { const pilot = await this.findPilot(context, pilotId); if (!pilot) throw new Error("PI_PILOT_NOT_FOUND"); if (pilot.status === "exited") return pilot; const updated = { ...pilot, status: "exited" as const, exitedAt }; this.pilots.set(`${context.tenantId}:${pilotId}`, updated); for (const [key, participant] of this.participants.entries()) if (participant.tenantId === context.tenantId && participant.pilotId === pilotId && participant.status === "active") this.participants.set(key, { ...participant, status: "revoked", revokedAt: exitedAt }); return clone(updated); }
  async putJourney(item: PiPilotJourney): Promise<void> { this.journeys.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listJourneys(context: RequestContext, pilotId: string): Promise<PiPilotJourney[]> { return [...this.journeys.values()].filter((item) => item.tenantId === context.tenantId && item.pilotId === pilotId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async putObservation(item: PiPilotObservation): Promise<void> { this.observations.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listObservations(context: RequestContext, pilotId: string): Promise<PiPilotObservation[]> { return [...this.observations.values()].filter((item) => item.tenantId === context.tenantId && item.pilotId === pilotId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async putDataSample(item: PiPilotDataSample): Promise<void> { this.dataSamples.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listDataSamples(context: RequestContext, pilotId: string): Promise<PiPilotDataSample[]> { return [...this.dataSamples.values()].filter((item) => item.tenantId === context.tenantId && item.pilotId === pilotId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async putIncident(item: PiPilotIncident): Promise<void> { this.incidents.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listIncidents(context: RequestContext, pilotId: string): Promise<PiPilotIncident[]> { return [...this.incidents.values()].filter((item) => item.tenantId === context.tenantId && item.pilotId === pilotId).sort((a, b) => b.openedAt.localeCompare(a.openedAt)).map(clone); }
  async putReadiness(item: PiPilotReadiness): Promise<void> { this.readiness.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async latestReadiness(context: RequestContext, pilotId: string): Promise<PiPilotReadiness | null> { const item = [...this.readiness.values()].filter((candidate) => candidate.tenantId === context.tenantId && candidate.pilotId === pilotId).sort((a, b) => b.generatedAt.localeCompare(a.generatedAt))[0]; return item ? clone(item) : null; }
  async listReadiness(context: RequestContext, limit = 100): Promise<PiPilotReadiness[]> { return [...this.readiness.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.generatedAt.localeCompare(a.generatedAt)).slice(0, limit).map(clone); }
  async appendEvent(item: PiPilotEvent): Promise<void> { this.events.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listEvents(context: RequestContext, limit = 100): Promise<PiPilotEvent[]> { return [...this.events.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map(clone); }
}

export class PostgresPiPilotStore implements PiPilotStore {
  constructor(private readonly database: TransactionalDatabase) {}
  private scoped<T>(context: RequestContext, work: (db: DatabaseExecutor) => Promise<T>): Promise<T> { return this.database.withTenant(context.tenantId, work); }
  private systemContext(tenantId: string, actorId: string, traceId: string): RequestContext { return { tenantId, actorId, sessionId: "system", channel: "system", traceId, roles: ["system"], permissions: [], dataScopes: [{ type: "tenant" }] }; }

  async putPilot(pilot: PiPilot): Promise<{ pilot: PiPilot; created: boolean }> { return this.scoped(this.systemContext(pilot.tenantId, pilot.createdBy, pilot.actionDigest), async (db) => { const rows = await db.query<Row>("INSERT INTO pi_pilots(id,tenant_id,created_by,project_id,name,version,starts_at,ends_at,exit_policy_digest,action_digest,status,created_at,exited_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(tenant_id,action_digest) DO NOTHING RETURNING *", [pilot.id, pilot.tenantId, pilot.createdBy, pilot.projectId, pilot.name, pilot.version, new Date(pilot.startsAt), new Date(pilot.endsAt), pilot.exitPolicyDigest, pilot.actionDigest, pilot.status, new Date(pilot.createdAt), pilot.exitedAt ? new Date(pilot.exitedAt) : null]); if (rows[0]) return { pilot: pilotFromRow(rows[0]), created: true }; const existing = await db.query<Row>("SELECT * FROM pi_pilots WHERE tenant_id=$1 AND action_digest=$2", [pilot.tenantId, pilot.actionDigest]); if (!existing[0]) throw new Error("PI_PILOT_WRITE_CONFLICT"); return { pilot: pilotFromRow(existing[0]), created: false }; }); }
  async findPilot(context: RequestContext, id: string): Promise<PiPilot | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_pilots WHERE tenant_id=$1 AND id=$2", [context.tenantId, id]); return rows[0] ? pilotFromRow(rows[0]) : null; }); }
  async findPilotByActionDigest(context: RequestContext, actionDigest: string): Promise<PiPilot | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_pilots WHERE tenant_id=$1 AND action_digest=$2", [context.tenantId, actionDigest]); return rows[0] ? pilotFromRow(rows[0]) : null; }); }
  async listPilots(context: RequestContext): Promise<PiPilot[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_pilots WHERE tenant_id=$1 ORDER BY created_at DESC", [context.tenantId])).map(pilotFromRow)); }
  async putParticipant(item: PiPilotParticipant): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.pilotId, item.id), async (db) => { await db.query("INSERT INTO pi_pilot_participants(id,tenant_id,pilot_id,subject_digest,role,project_scope_digest,status,created_at,revoked_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,pilot_id,subject_digest) DO NOTHING", [item.id, item.tenantId, item.pilotId, item.subjectDigest, item.role, item.projectScopeDigest, item.status, new Date(item.createdAt), item.revokedAt ? new Date(item.revokedAt) : null]); }); }
  async findParticipant(context: RequestContext, pilotId: string, participantId: string): Promise<PiPilotParticipant | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_pilot_participants WHERE tenant_id=$1 AND pilot_id=$2 AND id=$3", [context.tenantId, pilotId, participantId]); return rows[0] ? participantFromRow(rows[0]) : null; }); }
  async listParticipants(context: RequestContext, pilotId?: string): Promise<PiPilotParticipant[]> { return this.scoped(context, async (db) => (await db.query<Row>(`SELECT * FROM pi_pilot_participants WHERE tenant_id=$1${pilotId ? " AND pilot_id=$2" : ""} ORDER BY created_at DESC`, pilotId ? [context.tenantId, pilotId] : [context.tenantId])).map(participantFromRow)); }
  async revokeParticipant(context: RequestContext, pilotId: string, participantId: string, revokedAt: string): Promise<PiPilotParticipant> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("UPDATE pi_pilot_participants SET status='revoked',revoked_at=$4 WHERE tenant_id=$1 AND pilot_id=$2 AND id=$3 AND status='active' RETURNING *", [context.tenantId, pilotId, participantId, new Date(revokedAt)]); if (rows[0]) return participantFromRow(rows[0]); const current = await db.query<Row>("SELECT * FROM pi_pilot_participants WHERE tenant_id=$1 AND pilot_id=$2 AND id=$3", [context.tenantId, pilotId, participantId]); if (!current[0]) throw new Error("PI_PILOT_PARTICIPANT_NOT_FOUND"); return participantFromRow(current[0]); }); }
  async exitPilot(context: RequestContext, pilotId: string, exitedAt: string): Promise<PiPilot> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("UPDATE pi_pilots SET status='exited',exited_at=$3 WHERE tenant_id=$1 AND id=$2 AND status<>'exited' RETURNING *", [context.tenantId, pilotId, new Date(exitedAt)]); await db.query("UPDATE pi_pilot_participants SET status='revoked',revoked_at=$3 WHERE tenant_id=$1 AND pilot_id=$2 AND status='active'", [context.tenantId, pilotId, new Date(exitedAt)]); if (rows[0]) return pilotFromRow(rows[0]); const current = await db.query<Row>("SELECT * FROM pi_pilots WHERE tenant_id=$1 AND id=$2", [context.tenantId, pilotId]); if (!current[0]) throw new Error("PI_PILOT_NOT_FOUND"); return pilotFromRow(current[0]); }); }
  async putJourney(item: PiPilotJourney): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.pilotId, item.id), async (db) => { await db.query("INSERT INTO pi_pilot_journeys(id,tenant_id,pilot_id,kind,sample_digest,status,evidence_digest,run_digest,artifact_digest,quality_score,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)", [item.id, item.tenantId, item.pilotId, item.kind, item.sampleDigest, item.status, item.evidenceDigest ?? null, item.runDigest ?? null, item.artifactDigest ?? null, item.qualityScore ?? null, new Date(item.createdAt)]); }); }
  async listJourneys(context: RequestContext, pilotId: string): Promise<PiPilotJourney[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_pilot_journeys WHERE tenant_id=$1 AND pilot_id=$2 ORDER BY created_at DESC", [context.tenantId, pilotId])).map(journeyFromRow)); }
  async putObservation(item: PiPilotObservation): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.pilotId, item.id), async (db) => { await db.query("INSERT INTO pi_pilot_observations(id,tenant_id,pilot_id,metric,window_start,window_end,value,threshold,unit,status,evidence_digest,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)", [item.id, item.tenantId, item.pilotId, item.metric, new Date(item.windowStart), new Date(item.windowEnd), item.value, item.threshold, item.unit, item.status, item.evidenceDigest ?? null, new Date(item.createdAt)]); }); }
  async listObservations(context: RequestContext, pilotId: string): Promise<PiPilotObservation[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_pilot_observations WHERE tenant_id=$1 AND pilot_id=$2 ORDER BY created_at DESC", [context.tenantId, pilotId])).map(observationFromRow)); }
  async putDataSample(item: PiPilotDataSample): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.pilotId, item.id), async (db) => { await db.query("INSERT INTO pi_pilot_data_samples(id,tenant_id,pilot_id,classification,sample_digest,status,evidence_digest,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [item.id, item.tenantId, item.pilotId, item.classification, item.sampleDigest, item.status, item.evidenceDigest ?? null, new Date(item.createdAt)]); }); }
  async listDataSamples(context: RequestContext, pilotId: string): Promise<PiPilotDataSample[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_pilot_data_samples WHERE tenant_id=$1 AND pilot_id=$2 ORDER BY created_at DESC", [context.tenantId, pilotId])).map(dataSampleFromRow)); }
  async putIncident(item: PiPilotIncident): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.pilotId, item.id), async (db) => { await db.query("INSERT INTO pi_pilot_incidents(id,tenant_id,pilot_id,severity,status,summary_digest,opened_at,resolved_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [item.id, item.tenantId, item.pilotId, item.severity, item.status, item.summaryDigest, new Date(item.openedAt), item.resolvedAt ? new Date(item.resolvedAt) : null]); }); }
  async listIncidents(context: RequestContext, pilotId: string): Promise<PiPilotIncident[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_pilot_incidents WHERE tenant_id=$1 AND pilot_id=$2 ORDER BY opened_at DESC", [context.tenantId, pilotId])).map(incidentFromRow)); }
  async putReadiness(item: PiPilotReadiness): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.actorId, item.id), async (db) => { await db.query("INSERT INTO pi_pilot_readiness(id,tenant_id,actor_id,pilot_id,ready,checks,policy_version,generated_at,failure_digest) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9)", [item.id, item.tenantId, item.actorId, item.pilotId, item.ready, JSON.stringify(item.checks), item.policyVersion, new Date(item.generatedAt), item.failureDigest ?? null]); }); }
  async latestReadiness(context: RequestContext, pilotId: string): Promise<PiPilotReadiness | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_pilot_readiness WHERE tenant_id=$1 AND pilot_id=$2 ORDER BY generated_at DESC LIMIT 1", [context.tenantId, pilotId]); return rows[0] ? readinessFromRow(rows[0]) : null; }); }
  async listReadiness(context: RequestContext, limit = 100): Promise<PiPilotReadiness[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_pilot_readiness WHERE tenant_id=$1 ORDER BY generated_at DESC LIMIT $2", [context.tenantId, limit])).map(readinessFromRow)); }
  async appendEvent(item: PiPilotEvent): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.actorId, item.traceId), async (db) => { await db.query("INSERT INTO pi_pilot_events(id,tenant_id,actor_id,pilot_id,kind,subject_digest,trace_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [item.id, item.tenantId, item.actorId, item.pilotId, item.kind, item.subjectDigest, item.traceId, new Date(item.createdAt)]); }); }
  async listEvents(context: RequestContext, limit = 100): Promise<PiPilotEvent[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_pilot_events WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", [context.tenantId, limit])).map(eventFromRow)); }
}
