import type { RequestContext } from "@/src/platform/context/request-context";
import type { DatabaseExecutor, TransactionalDatabase } from "@/src/platform/database/executor";
import type {
  PiGateAttestation,
  PiPublication,
  PiReleaseApproval,
  PiReleaseEvaluation,
  PiReleaseGateEvaluation,
  PiReleaseGovernanceEvent,
  PiReleaseGovernanceStore,
  PiReleaseRisk,
  PiRollout,
} from "@/src/modules/pi-agent/domain/release-governance-contracts";

type Row = Record<string, unknown>;
const clone = <T>(value: T): T => structuredClone(value);
const text = (value: unknown): string => value instanceof Date ? value.toISOString() : String(value);
const optionalText = (value: unknown): string | undefined => value === null || value === undefined ? undefined : text(value);
const iso = (value: unknown): string => new Date(String(value)).toISOString();
const jsonValue = <T>(value: unknown): T => typeof value === "string" ? JSON.parse(value) as T : value as T;

function publicationFromRow(row: Row): PiPublication { return { id: text(row.id), tenantId: text(row.tenant_id), createdBy: text(row.created_by), version: text(row.version), upstreamVersion: text(row.upstream_version), apiDigest: text(row.api_digest), schemaDigest: text(row.schema_digest), imageDigest: text(row.image_digest), signatureDigest: text(row.signature_digest), sbomDigest: text(row.sbom_digest), rollbackDigest: text(row.rollback_digest), ...(optionalText(row.pilot_readiness_digest) ? { pilotReadinessDigest: text(row.pilot_readiness_digest) } : {}), actionDigest: text(row.action_digest), status: row.status as PiPublication["status"], createdAt: iso(row.created_at), ...(row.approved_at ? { approvedAt: iso(row.approved_at) } : {}), ...(row.revoked_at ? { revokedAt: iso(row.revoked_at) } : {}) }; }
function gateFromRow(row: Row): PiGateAttestation { return { id: text(row.id), tenantId: text(row.tenant_id), publicationId: text(row.publication_id), gateId: text(row.gate_id), status: row.status as PiGateAttestation["status"], evidenceDigest: text(row.evidence_digest), policyVersion: Number(row.policy_version), validUntil: iso(row.valid_until), createdBy: text(row.created_by), createdAt: iso(row.created_at) }; }
function riskFromRow(row: Row): PiReleaseRisk { return { id: text(row.id), tenantId: text(row.tenant_id), publicationId: text(row.publication_id), severity: row.severity as PiReleaseRisk["severity"], status: row.status as PiReleaseRisk["status"], summaryDigest: text(row.summary_digest), ...(optionalText(row.mitigation_digest) ? { mitigationDigest: text(row.mitigation_digest) } : {}), createdBy: text(row.created_by), createdAt: iso(row.created_at), ...(row.resolved_at ? { resolvedAt: iso(row.resolved_at) } : {}) }; }
function approvalFromRow(row: Row): PiReleaseApproval { return { id: text(row.id), tenantId: text(row.tenant_id), publicationId: text(row.publication_id), actorId: text(row.actor_id), role: row.role as PiReleaseApproval["role"], decision: row.decision as PiReleaseApproval["decision"], proposalHash: text(row.proposal_hash), expiresAt: iso(row.expires_at), createdAt: iso(row.created_at) }; }
function rolloutFromRow(row: Row): PiRollout { return { id: text(row.id), tenantId: text(row.tenant_id), publicationId: text(row.publication_id), scopeDigest: text(row.scope_digest), capabilityDigest: text(row.capability_digest), stage: row.stage as PiRollout["stage"], status: row.status as PiRollout["status"], previousVersionDigest: text(row.previous_version_digest), actionDigest: text(row.action_digest), createdAt: iso(row.created_at), changedAt: iso(row.changed_at) }; }
function releaseEvaluationFromRow(row: Row): PiReleaseEvaluation { return { id: text(row.id), tenantId: text(row.tenant_id), publicationId: text(row.publication_id), status: row.status as PiReleaseEvaluation["status"], suiteDigest: text(row.suite_digest), score: Number(row.score), threshold: Number(row.threshold), evidenceDigest: text(row.evidence_digest), createdAt: iso(row.created_at) }; }
function gateEvaluationFromRow(row: Row): PiReleaseGateEvaluation { return { id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), publicationId: text(row.publication_id), ready: Boolean(row.ready), checks: jsonValue<PiReleaseGateEvaluation["checks"]>(row.checks), policyVersion: Number(row.policy_version), generatedAt: iso(row.generated_at), ...(optionalText(row.failure_digest) ? { failureDigest: text(row.failure_digest) } : {}) }; }
function eventFromRow(row: Row): PiReleaseGovernanceEvent { return { id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), publicationId: text(row.publication_id), kind: row.kind as PiReleaseGovernanceEvent["kind"], subjectDigest: text(row.subject_digest), traceId: text(row.trace_id), createdAt: iso(row.created_at) }; }

export class InMemoryPiReleaseGovernanceStore implements PiReleaseGovernanceStore {
  private readonly publications = new Map<string, PiPublication>();
  private readonly gates = new Map<string, PiGateAttestation>();
  private readonly risks = new Map<string, PiReleaseRisk>();
  private readonly approvals = new Map<string, PiReleaseApproval>();
  private readonly rollouts = new Map<string, PiRollout>();
  private readonly evaluations = new Map<string, PiReleaseEvaluation>();
  private readonly gateEvaluations = new Map<string, PiReleaseGateEvaluation>();
  private readonly events = new Map<string, PiReleaseGovernanceEvent>();
  async putPublication(item: PiPublication): Promise<{ publication: PiPublication; created: boolean }> { const existing = [...this.publications.values()].find((candidate) => candidate.tenantId === item.tenantId && candidate.actionDigest === item.actionDigest); if (existing) return { publication: clone(existing), created: false }; this.publications.set(`${item.tenantId}:${item.id}`, clone(item)); return { publication: clone(item), created: true }; }
  async findPublication(context: RequestContext, id: string): Promise<PiPublication | null> { const item = this.publications.get(`${context.tenantId}:${id}`); return item ? clone(item) : null; }
  async findPublicationByActionDigest(context: RequestContext, actionDigest: string): Promise<PiPublication | null> { const item = [...this.publications.values()].find((candidate) => candidate.tenantId === context.tenantId && candidate.actionDigest === actionDigest); return item ? clone(item) : null; }
  async listPublications(context: RequestContext): Promise<PiPublication[]> { return [...this.publications.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async updatePublication(context: RequestContext, id: string, patch: Partial<Pick<PiPublication, "status" | "approvedAt" | "revokedAt">>): Promise<PiPublication> { const item = await this.findPublication(context, id); if (!item) throw new Error("PI_PUBLICATION_NOT_FOUND"); const updated = { ...item, ...patch }; this.publications.set(`${context.tenantId}:${id}`, updated); return clone(updated); }
  async putGate(item: PiGateAttestation): Promise<void> { this.gates.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listGates(context: RequestContext, publicationId: string): Promise<PiGateAttestation[]> { return [...this.gates.values()].filter((item) => item.tenantId === context.tenantId && item.publicationId === publicationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async putRisk(item: PiReleaseRisk): Promise<void> { this.risks.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listRisks(context: RequestContext, publicationId: string): Promise<PiReleaseRisk[]> { return [...this.risks.values()].filter((item) => item.tenantId === context.tenantId && item.publicationId === publicationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async resolveRisk(context: RequestContext, publicationId: string, riskId: string, mitigationDigest: string, resolvedAt: string): Promise<PiReleaseRisk> { const item = this.risks.get(`${context.tenantId}:${riskId}`); if (!item || item.publicationId !== publicationId) throw new Error("PI_RELEASE_RISK_NOT_FOUND"); if (item.status !== "open") return clone(item); const updated = { ...item, status: "mitigated" as const, mitigationDigest, resolvedAt }; this.risks.set(`${context.tenantId}:${riskId}`, updated); return clone(updated); }
  async putApproval(item: PiReleaseApproval): Promise<void> { this.approvals.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listApprovals(context: RequestContext, publicationId: string): Promise<PiReleaseApproval[]> { return [...this.approvals.values()].filter((item) => item.tenantId === context.tenantId && item.publicationId === publicationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async putRollout(item: PiRollout): Promise<void> { this.rollouts.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async findRollout(context: RequestContext, rolloutId: string): Promise<PiRollout | null> { const item = this.rollouts.get(`${context.tenantId}:${rolloutId}`); return item ? clone(item) : null; }
  async listRollouts(context: RequestContext, publicationId?: string): Promise<PiRollout[]> { return [...this.rollouts.values()].filter((item) => item.tenantId === context.tenantId && (!publicationId || item.publicationId === publicationId)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async updateRollout(context: RequestContext, rolloutId: string, patch: Partial<Pick<PiRollout, "stage" | "status" | "changedAt">>): Promise<PiRollout> { const item = await this.findRollout(context, rolloutId); if (!item) throw new Error("PI_ROLLOUT_NOT_FOUND"); const updated = { ...item, ...patch }; this.rollouts.set(`${context.tenantId}:${rolloutId}`, updated); return clone(updated); }
  async putEvaluation(item: PiReleaseEvaluation): Promise<void> { this.evaluations.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listEvaluations(context: RequestContext, publicationId?: string): Promise<PiReleaseEvaluation[]> { return [...this.evaluations.values()].filter((item) => item.tenantId === context.tenantId && (!publicationId || item.publicationId === publicationId)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(clone); }
  async putGateEvaluation(item: PiReleaseGateEvaluation): Promise<void> { this.gateEvaluations.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async latestGateEvaluation(context: RequestContext, publicationId: string): Promise<PiReleaseGateEvaluation | null> { const item = [...this.gateEvaluations.values()].filter((candidate) => candidate.tenantId === context.tenantId && candidate.publicationId === publicationId).sort((a, b) => b.generatedAt.localeCompare(a.generatedAt))[0]; return item ? clone(item) : null; }
  async listGateEvaluations(context: RequestContext, limit = 100): Promise<PiReleaseGateEvaluation[]> { return [...this.gateEvaluations.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.generatedAt.localeCompare(a.generatedAt)).slice(0, limit).map(clone); }
  async appendEvent(item: PiReleaseGovernanceEvent): Promise<void> { this.events.set(`${item.tenantId}:${item.id}`, clone(item)); }
  async listEvents(context: RequestContext, limit = 100): Promise<PiReleaseGovernanceEvent[]> { return [...this.events.values()].filter((item) => item.tenantId === context.tenantId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map(clone); }
}

export class PostgresPiReleaseGovernanceStore implements PiReleaseGovernanceStore {
  constructor(private readonly database: TransactionalDatabase) {}
  private scoped<T>(context: RequestContext, work: (db: DatabaseExecutor) => Promise<T>): Promise<T> { return this.database.withTenant(context.tenantId, work); }
  private systemContext(tenantId: string, actorId: string, traceId: string): RequestContext { return { tenantId, actorId, sessionId: "system", channel: "system", traceId, roles: ["system"], permissions: [], dataScopes: [{ type: "tenant" }] }; }
  async putPublication(item: PiPublication): Promise<{ publication: PiPublication; created: boolean }> { return this.scoped(this.systemContext(item.tenantId, item.createdBy, item.actionDigest), async (db) => { const rows = await db.query<Row>("INSERT INTO pi_publications(id,tenant_id,created_by,version,upstream_version,api_digest,schema_digest,image_digest,signature_digest,sbom_digest,rollback_digest,pilot_readiness_digest,action_digest,status,created_at,approved_at,revoked_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT(tenant_id,action_digest) DO NOTHING RETURNING *", [item.id, item.tenantId, item.createdBy, item.version, item.upstreamVersion, item.apiDigest, item.schemaDigest, item.imageDigest, item.signatureDigest, item.sbomDigest, item.rollbackDigest, item.pilotReadinessDigest ?? null, item.actionDigest, item.status, new Date(item.createdAt), item.approvedAt ? new Date(item.approvedAt) : null, item.revokedAt ? new Date(item.revokedAt) : null]); if (rows[0]) return { publication: publicationFromRow(rows[0]), created: true }; const existing = await db.query<Row>("SELECT * FROM pi_publications WHERE tenant_id=$1 AND action_digest=$2", [item.tenantId, item.actionDigest]); if (!existing[0]) throw new Error("PI_PUBLICATION_WRITE_CONFLICT"); return { publication: publicationFromRow(existing[0]), created: false }; }); }
  async findPublication(context: RequestContext, id: string): Promise<PiPublication | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_publications WHERE tenant_id=$1 AND id=$2", [context.tenantId, id]); return rows[0] ? publicationFromRow(rows[0]) : null; }); }
  async findPublicationByActionDigest(context: RequestContext, actionDigest: string): Promise<PiPublication | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_publications WHERE tenant_id=$1 AND action_digest=$2", [context.tenantId, actionDigest]); return rows[0] ? publicationFromRow(rows[0]) : null; }); }
  async listPublications(context: RequestContext): Promise<PiPublication[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_publications WHERE tenant_id=$1 ORDER BY created_at DESC", [context.tenantId])).map(publicationFromRow)); }
  async updatePublication(context: RequestContext, id: string, patch: Partial<Pick<PiPublication, "status" | "approvedAt" | "revokedAt">>): Promise<PiPublication> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("UPDATE pi_publications SET status=COALESCE($3,status),approved_at=COALESCE($4,approved_at),revoked_at=COALESCE($5,revoked_at) WHERE tenant_id=$1 AND id=$2 RETURNING *", [context.tenantId, id, patch.status ?? null, patch.approvedAt ? new Date(patch.approvedAt) : null, patch.revokedAt ? new Date(patch.revokedAt) : null]); if (!rows[0]) throw new Error("PI_PUBLICATION_NOT_FOUND"); return publicationFromRow(rows[0]); }); }
  async putGate(item: PiGateAttestation): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.createdBy, item.id), async (db) => { await db.query("INSERT INTO pi_gate_attestations(id,tenant_id,publication_id,gate_id,status,evidence_digest,policy_version,valid_until,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)", [item.id, item.tenantId, item.publicationId, item.gateId, item.status, item.evidenceDigest, item.policyVersion, new Date(item.validUntil), item.createdBy, new Date(item.createdAt)]); }); }
  async listGates(context: RequestContext, publicationId: string): Promise<PiGateAttestation[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_gate_attestations WHERE tenant_id=$1 AND publication_id=$2 ORDER BY created_at DESC", [context.tenantId, publicationId])).map(gateFromRow)); }
  async putRisk(item: PiReleaseRisk): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.createdBy, item.id), async (db) => { await db.query("INSERT INTO pi_release_risks(id,tenant_id,publication_id,severity,status,summary_digest,mitigation_digest,created_by,created_at,resolved_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)", [item.id, item.tenantId, item.publicationId, item.severity, item.status, item.summaryDigest, item.mitigationDigest ?? null, item.createdBy, new Date(item.createdAt), item.resolvedAt ? new Date(item.resolvedAt) : null]); }); }
  async listRisks(context: RequestContext, publicationId: string): Promise<PiReleaseRisk[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_release_risks WHERE tenant_id=$1 AND publication_id=$2 ORDER BY created_at DESC", [context.tenantId, publicationId])).map(riskFromRow)); }
  async resolveRisk(context: RequestContext, publicationId: string, riskId: string, mitigationDigest: string, resolvedAt: string): Promise<PiReleaseRisk> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("UPDATE pi_release_risks SET status='mitigated',mitigation_digest=$4,resolved_at=$5 WHERE tenant_id=$1 AND publication_id=$2 AND id=$3 AND status='open' RETURNING *", [context.tenantId, publicationId, riskId, mitigationDigest, new Date(resolvedAt)]); if (rows[0]) return riskFromRow(rows[0]); const current = await db.query<Row>("SELECT * FROM pi_release_risks WHERE tenant_id=$1 AND publication_id=$2 AND id=$3", [context.tenantId, publicationId, riskId]); if (!current[0]) throw new Error("PI_RELEASE_RISK_NOT_FOUND"); return riskFromRow(current[0]); }); }
  async putApproval(item: PiReleaseApproval): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.actorId, item.id), async (db) => { await db.query("INSERT INTO pi_release_approvals(id,tenant_id,publication_id,actor_id,role,decision,proposal_hash,expires_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)", [item.id, item.tenantId, item.publicationId, item.actorId, item.role, item.decision, item.proposalHash, new Date(item.expiresAt), new Date(item.createdAt)]); }); }
  async listApprovals(context: RequestContext, publicationId: string): Promise<PiReleaseApproval[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_release_approvals WHERE tenant_id=$1 AND publication_id=$2 ORDER BY created_at DESC", [context.tenantId, publicationId])).map(approvalFromRow)); }
  async putRollout(item: PiRollout): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.publicationId, item.id), async (db) => { await db.query("INSERT INTO pi_rollouts(id,tenant_id,publication_id,scope_digest,capability_digest,stage,status,previous_version_digest,action_digest,created_at,changed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)", [item.id, item.tenantId, item.publicationId, item.scopeDigest, item.capabilityDigest, item.stage, item.status, item.previousVersionDigest, item.actionDigest, new Date(item.createdAt), new Date(item.changedAt)]); }); }
  async findRollout(context: RequestContext, rolloutId: string): Promise<PiRollout | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_rollouts WHERE tenant_id=$1 AND id=$2", [context.tenantId, rolloutId]); return rows[0] ? rolloutFromRow(rows[0]) : null; }); }
  async listRollouts(context: RequestContext, publicationId?: string): Promise<PiRollout[]> { return this.scoped(context, async (db) => (await db.query<Row>(`SELECT * FROM pi_rollouts WHERE tenant_id=$1${publicationId ? " AND publication_id=$2" : ""} ORDER BY created_at DESC`, publicationId ? [context.tenantId, publicationId] : [context.tenantId])).map(rolloutFromRow)); }
  async updateRollout(context: RequestContext, rolloutId: string, patch: Partial<Pick<PiRollout, "stage" | "status" | "changedAt">>): Promise<PiRollout> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("UPDATE pi_rollouts SET stage=COALESCE($3,stage),status=COALESCE($4,status),changed_at=COALESCE($5,changed_at) WHERE tenant_id=$1 AND id=$2 RETURNING *", [context.tenantId, rolloutId, patch.stage ?? null, patch.status ?? null, patch.changedAt ? new Date(patch.changedAt) : null]); if (!rows[0]) throw new Error("PI_ROLLOUT_NOT_FOUND"); return rolloutFromRow(rows[0]); }); }
  async putEvaluation(item: PiReleaseEvaluation): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.publicationId, item.id), async (db) => { await db.query("INSERT INTO pi_release_evaluations(id,tenant_id,publication_id,status,suite_digest,score,threshold,evidence_digest,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)", [item.id, item.tenantId, item.publicationId, item.status, item.suiteDigest, item.score, item.threshold, item.evidenceDigest, new Date(item.createdAt)]); }); }
  async listEvaluations(context: RequestContext, publicationId?: string): Promise<PiReleaseEvaluation[]> { return this.scoped(context, async (db) => (await db.query<Row>(`SELECT * FROM pi_release_evaluations WHERE tenant_id=$1${publicationId ? " AND publication_id=$2" : ""} ORDER BY created_at DESC`, publicationId ? [context.tenantId, publicationId] : [context.tenantId])).map(releaseEvaluationFromRow)); }
  async putGateEvaluation(item: PiReleaseGateEvaluation): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.actorId, item.id), async (db) => { await db.query("INSERT INTO pi_release_gate_evaluations(id,tenant_id,actor_id,publication_id,ready,checks,policy_version,generated_at,failure_digest) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9)", [item.id, item.tenantId, item.actorId, item.publicationId, item.ready, JSON.stringify(item.checks), item.policyVersion, new Date(item.generatedAt), item.failureDigest ?? null]); }); }
  async latestGateEvaluation(context: RequestContext, publicationId: string): Promise<PiReleaseGateEvaluation | null> { return this.scoped(context, async (db) => { const rows = await db.query<Row>("SELECT * FROM pi_release_gate_evaluations WHERE tenant_id=$1 AND publication_id=$2 ORDER BY generated_at DESC LIMIT 1", [context.tenantId, publicationId]); return rows[0] ? gateEvaluationFromRow(rows[0]) : null; }); }
  async listGateEvaluations(context: RequestContext, limit = 100): Promise<PiReleaseGateEvaluation[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_release_gate_evaluations WHERE tenant_id=$1 ORDER BY generated_at DESC LIMIT $2", [context.tenantId, limit])).map(gateEvaluationFromRow)); }
  async appendEvent(item: PiReleaseGovernanceEvent): Promise<void> { await this.scoped(this.systemContext(item.tenantId, item.actorId, item.traceId), async (db) => { await db.query("INSERT INTO pi_release_governance_events(id,tenant_id,actor_id,publication_id,kind,subject_digest,trace_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [item.id, item.tenantId, item.actorId, item.publicationId, item.kind, item.subjectDigest, item.traceId, new Date(item.createdAt)]); }); }
  async listEvents(context: RequestContext, limit = 100): Promise<PiReleaseGovernanceEvent[]> { return this.scoped(context, async (db) => (await db.query<Row>("SELECT * FROM pi_release_governance_events WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", [context.tenantId, limit])).map(eventFromRow)); }
}
