import type { RequestContext } from "@/src/platform/context/request-context";
import type { DatabaseExecutor, SqlPrimitive, TransactionalDatabase } from "@/src/platform/database/executor";
import type {
  PiChangeDeliveryStore,
  PiChangeSubmission,
  PiDeliveryEvent,
  PiDeliveryOutbox,
  PiMergeProposal,
  PiProposalStatus,
  PiPullRequest,
  PiPullRequestStatus,
  PiReleaseProposal,
  PiDeliveryOutboxStatus,
  PiMergeability,
} from "@/src/modules/pi-agent/domain/change-delivery-contracts";

type Row = Record<string, unknown>;

function json<T>(value: unknown, fallback: T): T {
  if (typeof value === "string") {
    try { return JSON.parse(value) as T; } catch { return fallback; }
  }
  return (value as T) ?? fallback;
}

function text(value: unknown): string { return String(value); }
function optionalText(value: unknown): string | undefined { return value === null || value === undefined ? undefined : String(value); }
function iso(value: unknown): string { return new Date(String(value)).toISOString(); }

function submissionFromRow(row: Row): PiChangeSubmission {
  return {
    id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), sessionId: text(row.pi_session_id), runId: text(row.pi_run_id), workspaceRecordId: text(row.pi_workspace_id), repositoryId: text(row.repository_id),
    baseCommitSha: text(row.base_commit_sha), headCommitSha: text(row.head_commit_sha), branch: text(row.branch), targetBranch: text(row.target_branch), diffDigest: text(row.diff_digest), changeSetDigest: text(row.change_set_digest), validationDigest: text(row.validation_digest),
    checkpointIds: json<string[]>(row.checkpoint_ids, []), checks: json<PiChangeSubmission["checks"]>(row.checks, []), approvalId: text(row.approval_id), approvalHash: text(row.approval_hash), status: row.status as PiChangeSubmission["status"], version: Number(row.version), idempotencyKey: text(row.idempotency_key), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at),
  };
}

function pullRequestFromRow(row: Row): PiPullRequest {
  return {
    id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), submissionId: text(row.submission_id), provider: row.provider as PiPullRequest["provider"], repositoryId: text(row.repository_id), repositoryRef: text(row.repository_ref), branch: text(row.branch), targetBranch: text(row.target_branch), baseCommitSha: text(row.base_commit_sha), headCommitSha: text(row.head_commit_sha),
    ...(optionalText(row.external_id) ? { externalId: optionalText(row.external_id) } : {}), ...(optionalText(row.external_url) ? { externalUrl: optionalText(row.external_url) } : {}), status: row.status as PiPullRequestStatus, mergeability: row.mergeability as PiMergeability, version: Number(row.version), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at),
  };
}

function mergeProposalFromRow(row: Row): PiMergeProposal {
  return {
    id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), sessionId: text(row.pi_session_id), runId: text(row.pi_run_id), submissionId: text(row.submission_id), pullRequestId: text(row.pull_request_id), targetBranch: text(row.target_branch), approvalId: text(row.approval_id), proposalHash: text(row.proposal_hash), expectedObjectVersions: json(row.expected_object_versions, {}), status: row.status as PiProposalStatus, version: Number(row.version), idempotencyKey: text(row.idempotency_key), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at),
  };
}

function releaseProposalFromRow(row: Row): PiReleaseProposal {
  return {
    id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), sessionId: text(row.pi_session_id), runId: text(row.pi_run_id), submissionId: text(row.submission_id), ...(optionalText(row.pull_request_id) ? { pullRequestId: optionalText(row.pull_request_id) } : {}), environment: text(row.environment), artifactDigest: text(row.artifact_digest), approvalId: text(row.approval_id), proposalHash: text(row.proposal_hash), expectedObjectVersions: json(row.expected_object_versions, {}), status: row.status as PiProposalStatus, version: Number(row.version), idempotencyKey: text(row.idempotency_key), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at),
  };
}

function outboxFromRow(row: Row): PiDeliveryOutbox {
  return {
    id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), sessionId: text(row.pi_session_id), runId: text(row.pi_run_id), actionType: row.action_type as PiDeliveryOutbox["actionType"], entityId: text(row.entity_id),
    ...(optionalText(row.approval_id) ? { approvalId: optionalText(row.approval_id) } : {}), ...(optionalText(row.proposal_hash) ? { proposalHash: optionalText(row.proposal_hash) } : {}), status: row.status as PiDeliveryOutboxStatus, attempts: Number(row.attempts), maxAttempts: Number(row.max_attempts), ...(optionalText(row.lease_owner) ? { leaseOwner: optionalText(row.lease_owner) } : {}), ...(optionalText(row.lease_token) ? { leaseToken: optionalText(row.lease_token) } : {}), ...(row.lease_expires_at ? { leaseExpiresAt: iso(row.lease_expires_at) } : {}), idempotencyKey: text(row.idempotency_key), payloadDigest: text(row.payload_digest), ...(optionalText(row.external_id) ? { externalId: optionalText(row.external_id) } : {}), ...(optionalText(row.external_url) ? { externalUrl: optionalText(row.external_url) } : {}), ...(optionalText(row.result_digest) ? { resultDigest: optionalText(row.result_digest) } : {}), ...(optionalText(row.last_error_code) ? { lastErrorCode: optionalText(row.last_error_code) } : {}), version: Number(row.version), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at),
  };
}

function eventFromRow(row: Row): PiDeliveryEvent {
  return { id: text(row.id), tenantId: text(row.tenant_id), actorId: text(row.actor_id), sessionId: text(row.pi_session_id), runId: text(row.pi_run_id), actionType: row.action_type as PiDeliveryEvent["actionType"], entityId: text(row.entity_id), eventType: row.event_type as PiDeliveryEvent["eventType"], subjectDigest: text(row.subject_digest), traceId: text(row.trace_id), createdAt: iso(row.created_at) };
}

export class PostgresPiChangeDeliveryStore implements PiChangeDeliveryStore {
  constructor(private readonly database: TransactionalDatabase) {}

  private scoped<T>(context: RequestContext, work: (db: DatabaseExecutor) => Promise<T>): Promise<T> { return this.database.withTenant(context.tenantId, work); }
  private ownerPredicate(context: RequestContext, alias: string, actorPlaceholder = 3): { sql: string; params: SqlPrimitive[] } {
    const admin = context.channel === "system" || context.permissions.includes("pi:change:admin");
    return admin ? { sql: "", params: [] } : { sql: ` AND ${alias}.actor_id=$${actorPlaceholder}`, params: [context.actorId] };
  }

  async findSubmissionByIdempotency(context: RequestContext, idempotencyKey: string): Promise<PiChangeSubmission | null> {
    return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "s"); const rows = await db.query<Row>(`SELECT s.* FROM pi_change_submissions s WHERE s.tenant_id=$1 AND s.idempotency_key=$2${owner.sql}`, [context.tenantId, idempotencyKey, ...owner.params]); return rows[0] ? submissionFromRow(rows[0]) : null; });
  }

  async createSubmission(submission: PiChangeSubmission): Promise<{ submission: PiChangeSubmission; created: boolean }> {
    const rows = await this.database.withTenant(submission.tenantId, (db) => db.query<Row>(
      `INSERT INTO pi_change_submissions
       (id,tenant_id,actor_id,pi_session_id,pi_run_id,pi_workspace_id,repository_id,base_commit_sha,head_commit_sha,branch,target_branch,diff_digest,change_set_digest,validation_digest,checkpoint_ids,checks,approval_id,approval_hash,status,version,idempotency_key)
       VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)
       ON CONFLICT (tenant_id,idempotency_key) DO NOTHING RETURNING *`,
      [submission.id, submission.tenantId, submission.actorId, submission.sessionId, submission.runId, submission.workspaceRecordId, submission.repositoryId, submission.baseCommitSha, submission.headCommitSha, submission.branch, submission.targetBranch, submission.diffDigest, submission.changeSetDigest, submission.validationDigest, JSON.stringify(submission.checkpointIds), JSON.stringify(submission.checks), submission.approvalId, submission.approvalHash, submission.status, submission.version, submission.idempotencyKey],
    ));
    if (rows[0]) return { submission: submissionFromRow(rows[0]), created: true };
    const existing = await this.database.withTenant(submission.tenantId, (db) => db.query<Row>("SELECT * FROM pi_change_submissions WHERE tenant_id=$1 AND idempotency_key=$2", [submission.tenantId, submission.idempotencyKey]));
    if (!existing[0]) throw new Error("PI_CHANGE_SUBMISSION_WRITE_CONFLICT");
    return { submission: submissionFromRow(existing[0]), created: false };
  }

  async getSubmission(context: RequestContext, submissionId: string): Promise<PiChangeSubmission | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "s"); const rows = await db.query<Row>(`SELECT s.* FROM pi_change_submissions s WHERE s.tenant_id=$1 AND s.id=$2${owner.sql}`, [context.tenantId, submissionId, ...owner.params]); return rows[0] ? submissionFromRow(rows[0]) : null; }); }
  async listSubmissions(context: RequestContext): Promise<PiChangeSubmission[]> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "s", 2); const rows = await db.query<Row>(`SELECT s.* FROM pi_change_submissions s WHERE s.tenant_id=$1${owner.sql} ORDER BY s.created_at DESC`, [context.tenantId, ...owner.params]); return rows.map(submissionFromRow); }); }
  async updateSubmission(context: RequestContext, submissionId: string, expectedVersion: number, patch: { status: PiChangeSubmission["status"]; updatedAt: string }): Promise<PiChangeSubmission | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "s", 6); const rows = await db.query<Row>(`UPDATE pi_change_submissions s SET status=$4,version=s.version+1,updated_at=$5 WHERE s.tenant_id=$1 AND s.id=$2 AND s.version=$3${owner.sql} RETURNING s.*`, [context.tenantId, submissionId, expectedVersion, patch.status, new Date(patch.updatedAt), ...owner.params]); return rows[0] ? submissionFromRow(rows[0]) : null; }); }

  async getPullRequest(context: RequestContext, pullRequestId: string): Promise<PiPullRequest | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "p"); const rows = await db.query<Row>(`SELECT p.* FROM pi_pull_requests p WHERE p.tenant_id=$1 AND p.id=$2${owner.sql}`, [context.tenantId, pullRequestId, ...owner.params]); return rows[0] ? pullRequestFromRow(rows[0]) : null; }); }
  async getPullRequestForSubmission(context: RequestContext, submissionId: string): Promise<PiPullRequest | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "p"); const rows = await db.query<Row>(`SELECT p.* FROM pi_pull_requests p WHERE p.tenant_id=$1 AND p.submission_id=$2${owner.sql}`, [context.tenantId, submissionId, ...owner.params]); return rows[0] ? pullRequestFromRow(rows[0]) : null; }); }
  async listPullRequests(context: RequestContext): Promise<PiPullRequest[]> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "p", 2); const rows = await db.query<Row>(`SELECT p.* FROM pi_pull_requests p WHERE p.tenant_id=$1${owner.sql} ORDER BY p.created_at DESC`, [context.tenantId, ...owner.params]); return rows.map(pullRequestFromRow); }); }
  async createPullRequest(pullRequest: PiPullRequest): Promise<{ pullRequest: PiPullRequest; created: boolean }> { const rows = await this.database.withTenant(pullRequest.tenantId, (db) => db.query<Row>(`INSERT INTO pi_pull_requests (id,tenant_id,actor_id,submission_id,provider,repository_id,repository_ref,branch,target_branch,base_commit_sha,head_commit_sha,external_id,external_url,status,mergeability,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) ON CONFLICT (tenant_id,submission_id) DO NOTHING RETURNING *`, [pullRequest.id, pullRequest.tenantId, pullRequest.actorId, pullRequest.submissionId, pullRequest.provider, pullRequest.repositoryId, pullRequest.repositoryRef, pullRequest.branch, pullRequest.targetBranch, pullRequest.baseCommitSha, pullRequest.headCommitSha, pullRequest.externalId ?? null, pullRequest.externalUrl ?? null, pullRequest.status, pullRequest.mergeability, pullRequest.version])); if (rows[0]) return { pullRequest: pullRequestFromRow(rows[0]), created: true }; const existing = await this.database.withTenant(pullRequest.tenantId, (db) => db.query<Row>("SELECT * FROM pi_pull_requests WHERE tenant_id=$1 AND submission_id=$2", [pullRequest.tenantId, pullRequest.submissionId])); if (!existing[0]) throw new Error("PI_CHANGE_PULL_REQUEST_WRITE_CONFLICT"); return { pullRequest: pullRequestFromRow(existing[0]), created: false }; }
  async updatePullRequest(context: RequestContext, pullRequestId: string, expectedVersion: number, patch: Partial<Pick<PiPullRequest, "status" | "mergeability" | "externalId" | "externalUrl" | "updatedAt">>): Promise<PiPullRequest | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "p", 9); const rows = await db.query<Row>(`UPDATE pi_pull_requests p SET status=COALESCE($4,p.status),mergeability=COALESCE($5,p.mergeability),external_id=COALESCE($6,p.external_id),external_url=COALESCE($7,p.external_url),version=p.version+1,updated_at=COALESCE($8,now()) WHERE p.tenant_id=$1 AND p.id=$2 AND p.version=$3${owner.sql} RETURNING p.*`, [context.tenantId, pullRequestId, expectedVersion, patch.status ?? null, patch.mergeability ?? null, patch.externalId ?? null, patch.externalUrl ?? null, patch.updatedAt ? new Date(patch.updatedAt) : null, ...owner.params]); return rows[0] ? pullRequestFromRow(rows[0]) : null; }); }

  async findMergeProposalByIdempotency(context: RequestContext, idempotencyKey: string): Promise<PiMergeProposal | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "m"); const rows = await db.query<Row>(`SELECT m.* FROM pi_merge_proposals m WHERE m.tenant_id=$1 AND m.idempotency_key=$2${owner.sql}`, [context.tenantId, idempotencyKey, ...owner.params]); return rows[0] ? mergeProposalFromRow(rows[0]) : null; }); }
  async createMergeProposal(proposal: PiMergeProposal): Promise<{ proposal: PiMergeProposal; created: boolean }> { const rows = await this.database.withTenant(proposal.tenantId, (db) => db.query<Row>(`INSERT INTO pi_merge_proposals (id,tenant_id,actor_id,pi_session_id,pi_run_id,submission_id,pull_request_id,target_branch,approval_id,proposal_hash,expected_object_versions,status,version,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (tenant_id,idempotency_key) DO NOTHING RETURNING *`, [proposal.id, proposal.tenantId, proposal.actorId, proposal.sessionId, proposal.runId, proposal.submissionId, proposal.pullRequestId, proposal.targetBranch, proposal.approvalId, proposal.proposalHash, JSON.stringify(proposal.expectedObjectVersions), proposal.status, proposal.version, proposal.idempotencyKey])); if (rows[0]) return { proposal: mergeProposalFromRow(rows[0]), created: true }; const existing = await this.database.withTenant(proposal.tenantId, (db) => db.query<Row>("SELECT * FROM pi_merge_proposals WHERE tenant_id=$1 AND idempotency_key=$2", [proposal.tenantId, proposal.idempotencyKey])); if (!existing[0]) throw new Error("PI_CHANGE_MERGE_PROPOSAL_WRITE_CONFLICT"); return { proposal: mergeProposalFromRow(existing[0]), created: false }; }
  async getMergeProposal(context: RequestContext, proposalId: string): Promise<PiMergeProposal | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "m"); const rows = await db.query<Row>(`SELECT m.* FROM pi_merge_proposals m WHERE m.tenant_id=$1 AND m.id=$2${owner.sql}`, [context.tenantId, proposalId, ...owner.params]); return rows[0] ? mergeProposalFromRow(rows[0]) : null; }); }
  async listMergeProposals(context: RequestContext): Promise<PiMergeProposal[]> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "m", 2); const rows = await db.query<Row>(`SELECT m.* FROM pi_merge_proposals m WHERE m.tenant_id=$1${owner.sql} ORDER BY m.created_at DESC`, [context.tenantId, ...owner.params]); return rows.map(mergeProposalFromRow); }); }
  async updateMergeProposal(context: RequestContext, proposalId: string, expectedVersion: number, patch: { status: PiProposalStatus; updatedAt: string }): Promise<PiMergeProposal | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "m", 6); const rows = await db.query<Row>(`UPDATE pi_merge_proposals m SET status=$4,version=m.version+1,updated_at=$5 WHERE m.tenant_id=$1 AND m.id=$2 AND m.version=$3${owner.sql} RETURNING m.*`, [context.tenantId, proposalId, expectedVersion, patch.status, new Date(patch.updatedAt), ...owner.params]); return rows[0] ? mergeProposalFromRow(rows[0]) : null; }); }

  async findReleaseProposalByIdempotency(context: RequestContext, idempotencyKey: string): Promise<PiReleaseProposal | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "r"); const rows = await db.query<Row>(`SELECT r.* FROM pi_release_proposals r WHERE r.tenant_id=$1 AND r.idempotency_key=$2${owner.sql}`, [context.tenantId, idempotencyKey, ...owner.params]); return rows[0] ? releaseProposalFromRow(rows[0]) : null; }); }
  async createReleaseProposal(proposal: PiReleaseProposal): Promise<{ proposal: PiReleaseProposal; created: boolean }> { const rows = await this.database.withTenant(proposal.tenantId, (db) => db.query<Row>(`INSERT INTO pi_release_proposals (id,tenant_id,actor_id,pi_session_id,pi_run_id,submission_id,pull_request_id,environment,artifact_digest,approval_id,proposal_hash,expected_object_versions,status,version,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT (tenant_id,idempotency_key) DO NOTHING RETURNING *`, [proposal.id, proposal.tenantId, proposal.actorId, proposal.sessionId, proposal.runId, proposal.submissionId, proposal.pullRequestId ?? null, proposal.environment, proposal.artifactDigest, proposal.approvalId, proposal.proposalHash, JSON.stringify(proposal.expectedObjectVersions), proposal.status, proposal.version, proposal.idempotencyKey])); if (rows[0]) return { proposal: releaseProposalFromRow(rows[0]), created: true }; const existing = await this.database.withTenant(proposal.tenantId, (db) => db.query<Row>("SELECT * FROM pi_release_proposals WHERE tenant_id=$1 AND idempotency_key=$2", [proposal.tenantId, proposal.idempotencyKey])); if (!existing[0]) throw new Error("PI_CHANGE_RELEASE_PROPOSAL_WRITE_CONFLICT"); return { proposal: releaseProposalFromRow(existing[0]), created: false }; }
  async getReleaseProposal(context: RequestContext, proposalId: string): Promise<PiReleaseProposal | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "r"); const rows = await db.query<Row>(`SELECT r.* FROM pi_release_proposals r WHERE r.tenant_id=$1 AND r.id=$2${owner.sql}`, [context.tenantId, proposalId, ...owner.params]); return rows[0] ? releaseProposalFromRow(rows[0]) : null; }); }
  async listReleaseProposals(context: RequestContext): Promise<PiReleaseProposal[]> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "r", 2); const rows = await db.query<Row>(`SELECT r.* FROM pi_release_proposals r WHERE r.tenant_id=$1${owner.sql} ORDER BY r.created_at DESC`, [context.tenantId, ...owner.params]); return rows.map(releaseProposalFromRow); }); }
  async updateReleaseProposal(context: RequestContext, proposalId: string, expectedVersion: number, patch: { status: PiProposalStatus; updatedAt: string }): Promise<PiReleaseProposal | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "r", 6); const rows = await db.query<Row>(`UPDATE pi_release_proposals r SET status=$4,version=r.version+1,updated_at=$5 WHERE r.tenant_id=$1 AND r.id=$2 AND r.version=$3${owner.sql} RETURNING r.*`, [context.tenantId, proposalId, expectedVersion, patch.status, new Date(patch.updatedAt), ...owner.params]); return rows[0] ? releaseProposalFromRow(rows[0]) : null; }); }

  async findOutboxByIdempotency(context: RequestContext, idempotencyKey: string): Promise<PiDeliveryOutbox | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "o"); const rows = await db.query<Row>(`SELECT o.* FROM pi_delivery_outbox o WHERE o.tenant_id=$1 AND o.idempotency_key=$2${owner.sql}`, [context.tenantId, idempotencyKey, ...owner.params]); return rows[0] ? outboxFromRow(rows[0]) : null; }); }
  async createOutbox(outbox: PiDeliveryOutbox): Promise<{ outbox: PiDeliveryOutbox; created: boolean }> { const rows = await this.database.withTenant(outbox.tenantId, (db) => db.query<Row>(`INSERT INTO pi_delivery_outbox (id,tenant_id,actor_id,pi_session_id,pi_run_id,action_type,entity_id,approval_id,proposal_hash,status,attempts,max_attempts,idempotency_key,payload_digest,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT (tenant_id,idempotency_key) DO NOTHING RETURNING *`, [outbox.id, outbox.tenantId, outbox.actorId, outbox.sessionId, outbox.runId, outbox.actionType, outbox.entityId, outbox.approvalId ?? null, outbox.proposalHash ?? null, outbox.status, outbox.attempts, outbox.maxAttempts, outbox.idempotencyKey, outbox.payloadDigest, outbox.version])); if (rows[0]) return { outbox: outboxFromRow(rows[0]), created: true }; const existing = await this.database.withTenant(outbox.tenantId, (db) => db.query<Row>("SELECT * FROM pi_delivery_outbox WHERE tenant_id=$1 AND idempotency_key=$2", [outbox.tenantId, outbox.idempotencyKey])); if (!existing[0]) throw new Error("PI_CHANGE_OUTBOX_WRITE_CONFLICT"); return { outbox: outboxFromRow(existing[0]), created: false }; }
  async getOutbox(context: RequestContext, outboxId: string): Promise<PiDeliveryOutbox | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "o"); const rows = await db.query<Row>(`SELECT o.* FROM pi_delivery_outbox o WHERE o.tenant_id=$1 AND o.id=$2${owner.sql}`, [context.tenantId, outboxId, ...owner.params]); return rows[0] ? outboxFromRow(rows[0]) : null; }); }
  async listOutbox(context: RequestContext): Promise<PiDeliveryOutbox[]> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "o", 2); const rows = await db.query<Row>(`SELECT o.* FROM pi_delivery_outbox o WHERE o.tenant_id=$1${owner.sql} ORDER BY o.created_at DESC`, [context.tenantId, ...owner.params]); return rows.map(outboxFromRow); }); }
  async activateOutbox(context: RequestContext, outboxId: string, expectedVersion: number, updatedAt: string): Promise<PiDeliveryOutbox | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "o", 5); const rows = await db.query<Row>(`UPDATE pi_delivery_outbox o SET status='queued',version=o.version+1,updated_at=$4 WHERE o.tenant_id=$1 AND o.id=$2 AND o.version=$3 AND o.status='awaiting_approval'${owner.sql} RETURNING o.*`, [context.tenantId, outboxId, expectedVersion, new Date(updatedAt), ...owner.params]); return rows[0] ? outboxFromRow(rows[0]) : null; }); }
  async claimOutbox(context: RequestContext, outboxId: string, expectedVersion: number, nowValue: string, leaseOwner: string, leaseToken: string, leaseMs: number): Promise<PiDeliveryOutbox | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "o", 8); const now = new Date(nowValue); const expiresAt = new Date(now.getTime() + leaseMs); const rows = await db.query<Row>(`UPDATE pi_delivery_outbox o SET status='leased',attempts=o.attempts+1,lease_owner=$5,lease_token=$6,lease_expires_at=$7,version=o.version+1,updated_at=$4 WHERE o.tenant_id=$1 AND o.id=$2 AND o.version=$3 AND o.status IN ('queued','awaiting_approval')${owner.sql} RETURNING o.*`, [context.tenantId, outboxId, expectedVersion, now, leaseOwner, leaseToken, expiresAt, ...owner.params]); return rows[0] ? outboxFromRow(rows[0]) : null; }); }
  async reclaimExpiredOutbox(context: RequestContext, outboxId: string, expectedVersion: number, nowValue: string, leaseOwner: string, leaseToken: string, leaseMs: number): Promise<PiDeliveryOutbox | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "o", 8); const now = new Date(nowValue); const expiresAt = new Date(now.getTime() + leaseMs); const rows = await db.query<Row>(`UPDATE pi_delivery_outbox o SET status='leased',attempts=o.attempts+1,lease_owner=$5,lease_token=$6,lease_expires_at=$7,version=o.version+1,updated_at=$4 WHERE o.tenant_id=$1 AND o.id=$2 AND o.version=$3 AND o.status='leased' AND o.lease_expires_at <= $4${owner.sql} RETURNING o.*`, [context.tenantId, outboxId, expectedVersion, now, leaseOwner, leaseToken, expiresAt, ...owner.params]); return rows[0] ? outboxFromRow(rows[0]) : null; }); }
  async completeOutbox(context: RequestContext, outboxId: string, expectedVersion: number, input: { leaseToken: string; status: PiDeliveryOutboxStatus; resultDigest: string; externalId?: string; externalUrl?: string; lastErrorCode?: string; updatedAt: string }): Promise<PiDeliveryOutbox | null> { return this.scoped(context, async (db) => { const owner = this.ownerPredicate(context, "o", 11); const rows = await db.query<Row>(`UPDATE pi_delivery_outbox o SET status=$4,result_digest=$5,external_id=COALESCE($6,o.external_id),external_url=COALESCE($7,o.external_url),last_error_code=COALESCE($8,o.last_error_code),lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,version=o.version+1,updated_at=$9 WHERE o.tenant_id=$1 AND o.id=$2 AND o.version=$3 AND o.status='leased' AND o.lease_token=$10 AND o.lease_expires_at > $9${owner.sql} RETURNING o.*`, [context.tenantId, outboxId, expectedVersion, input.status, input.resultDigest, input.externalId ?? null, input.externalUrl ?? null, input.lastErrorCode ?? null, new Date(input.updatedAt), input.leaseToken, ...owner.params]); return rows[0] ? outboxFromRow(rows[0]) : null; }); }

  async appendEvent(event: PiDeliveryEvent): Promise<void> { await this.database.withTenant(event.tenantId, (db) => db.query(`INSERT INTO pi_delivery_events (id,tenant_id,actor_id,pi_session_id,pi_run_id,action_type,entity_id,event_type,subject_digest,trace_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`, [event.id, event.tenantId, event.actorId, event.sessionId, event.runId, event.actionType, event.entityId, event.eventType, event.subjectDigest, event.traceId, new Date(event.createdAt)]).then(() => undefined)); }
  async listEvents(context: RequestContext, limit = 200): Promise<PiDeliveryEvent[]> { return this.scoped(context, async (db) => { const admin = context.channel === "system" || context.permissions.includes("pi:change:admin"); const rows = await db.query<Row>(`SELECT e.* FROM pi_delivery_events e WHERE e.tenant_id=$1${admin ? "" : " AND e.actor_id=$2"} ORDER BY e.created_at DESC LIMIT ${Math.min(Math.max(limit, 1), 500)}`, admin ? [context.tenantId] : [context.tenantId, context.actorId]); return rows.map(eventFromRow); }); }
}
