const DATABASE_NAME="nexus-secure-drafts";const DATABASE_VERSION=1;const KEY_STORE="keys";const DRAFT_STORE="drafts";const AAD="nexus-offline-draft:v1";
export type OfflineDraft={id:string;title:string;body:string;classification:"internal";createdAt:string;expiresAt:string};
type StoredDraft={id:string;iv:string;ciphertext:string;createdAt:string;expiresAt:string};
const bytesToBase64=(value:Uint8Array)=>{let binary="";for(const byte of value)binary+=String.fromCharCode(byte);return btoa(binary);};
const base64ToBytes=(value:string)=>{const binary=atob(value);return Uint8Array.from(binary,char=>char.charCodeAt(0));};

export async function encryptOfflineDraft(draft:OfflineDraft,key:CryptoKey):Promise<StoredDraft>{if(draft.classification!=="internal")throw new Error("OFFLINE_CLASSIFICATION_DENIED");const iv=crypto.getRandomValues(new Uint8Array(12));const encoded=new TextEncoder().encode(JSON.stringify(draft));const ciphertext=await crypto.subtle.encrypt({name:"AES-GCM",iv,additionalData:new TextEncoder().encode(AAD)},key,encoded);return{id:draft.id,iv:bytesToBase64(iv),ciphertext:bytesToBase64(new Uint8Array(ciphertext)),createdAt:draft.createdAt,expiresAt:draft.expiresAt};}
export async function decryptOfflineDraft(stored:StoredDraft,key:CryptoKey):Promise<OfflineDraft>{try{const plaintext=await crypto.subtle.decrypt({name:"AES-GCM",iv:base64ToBytes(stored.iv),additionalData:new TextEncoder().encode(AAD)},key,base64ToBytes(stored.ciphertext));const draft=JSON.parse(new TextDecoder().decode(plaintext)) as OfflineDraft;if(draft.classification!=="internal"||draft.id!==stored.id)throw new Error();return draft;}catch{throw new Error("OFFLINE_DRAFT_DECRYPTION_FAILED");}}

function openDatabase():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DATABASE_NAME,DATABASE_VERSION);request.onupgradeneeded=()=>{const database=request.result;if(!database.objectStoreNames.contains(KEY_STORE))database.createObjectStore(KEY_STORE);if(!database.objectStoreNames.contains(DRAFT_STORE))database.createObjectStore(DRAFT_STORE,{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error("OFFLINE_STORAGE_UNAVAILABLE"));});}
function transactionRequest<T>(request:IDBRequest<T>):Promise<T>{return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error("OFFLINE_STORAGE_FAILED"));});}
async function deviceKey(database:IDBDatabase):Promise<CryptoKey>{const read=database.transaction(KEY_STORE,"readonly").objectStore(KEY_STORE).get("device-key");const existing=await transactionRequest(read) as CryptoKey|undefined;if(existing)return existing;const key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);const write=database.transaction(KEY_STORE,"readwrite").objectStore(KEY_STORE).put(key,"device-key");await transactionRequest(write);return key;}
export async function saveOfflineDraft(input:{title:string;body:string},now=new Date()):Promise<OfflineDraft>{const database=await openDatabase();try{const key=await deviceKey(database);const draft:OfflineDraft={id:crypto.randomUUID(),title:input.title,body:input.body,classification:"internal",createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+7*24*60*60*1000).toISOString()};const stored=await encryptOfflineDraft(draft,key);await transactionRequest(database.transaction(DRAFT_STORE,"readwrite").objectStore(DRAFT_STORE).put(stored));return draft;}finally{database.close();}}
export async function listOfflineDrafts(now=new Date()):Promise<OfflineDraft[]>{const database=await openDatabase();try{const key=await deviceKey(database);const stored=await transactionRequest(database.transaction(DRAFT_STORE,"readonly").objectStore(DRAFT_STORE).getAll()) as StoredDraft[];const active:OfflineDraft[]=[];for(const item of stored){if(new Date(item.expiresAt)<=now){await transactionRequest(database.transaction(DRAFT_STORE,"readwrite").objectStore(DRAFT_STORE).delete(item.id));continue;}active.push(await decryptOfflineDraft(item,key));}return active.sort((left,right)=>right.createdAt.localeCompare(left.createdAt));}finally{database.close();}}
export async function deleteOfflineDraft(id:string):Promise<void>{const database=await openDatabase();try{await transactionRequest(database.transaction(DRAFT_STORE,"readwrite").objectStore(DRAFT_STORE).delete(id));}finally{database.close();}}
export async function clearOfflineData():Promise<void>{await new Promise<void>((resolve,reject)=>{const request=indexedDB.deleteDatabase(DATABASE_NAME);request.onsuccess=()=>resolve();request.onerror=()=>reject(new Error("OFFLINE_STORAGE_CLEAR_FAILED"));request.onblocked=()=>reject(new Error("OFFLINE_STORAGE_CLEAR_BLOCKED"));});}
