// Requirements: PR-004, PR-007, PR-008, AR-011, AR-012, SR-001, SR-003, SR-005, AC-008
import { describe,expect,it } from "vitest";
import { ClientPlatformService } from "@/src/modules/client-platform/application/service";
import { registerClientDeviceSchema } from "@/src/modules/client-platform/application/schemas";
import { InMemoryClientPlatformRepository } from "@/src/modules/client-platform/infrastructure/in-memory-repository";
import { compareVersions } from "@/src/modules/client-platform/domain/client-device";
import { createDevelopmentRequestContext } from "@/src/platform/context/development-context";
import { decryptSensitiveJson,encryptSensitiveJson,sensitiveValueDigest } from "@/src/platform/security/encrypted-envelope";
import { decryptOfflineDraft,encryptOfflineDraft } from "@/src/client/offline-draft-store";

const input={installationId:"11000000-0000-4000-8000-000000000001",displayName:"管理者手机",clientType:"mobile_pwa" as const,platform:"Android",appVersion:"0.9.0"};

describe("client platform governance",()=>{
  it("registers an unmanaged device without accepting client-supplied trust and enables policy-scoped features",async()=>{const repository=new InMemoryClientPlatformRepository();const service=new ClientPlatformService(repository,{minimumVersion:"0.9.0",managedDeviceRequired:false,offlineDrafts:"internal",pushEnabled:true,pushPublicKey:"public",draftRetentionDays:7});const context=createDevelopmentRequestContext();expect(()=>registerClientDeviceSchema.parse({...input,trustLevel:"attested",tenantId:"attacker"})).toThrow();const device=await service.registerDevice(context,input,new Date("2026-08-05T00:00:00Z"));expect(device).toMatchObject({trustLevel:"unmanaged",status:"active",tenantId:context.tenantId,userId:context.actorId});expect(await service.bootstrap(context,input.installationId,"0.9.0")).toMatchObject({versionSupported:true,features:{offlineDrafts:true,push:true}});});
  it("keeps unmanaged devices pending when enterprise policy requires managed trust",async()=>{const service=new ClientPlatformService(new InMemoryClientPlatformRepository(),{minimumVersion:"0.9.0",managedDeviceRequired:true,offlineDrafts:"internal",pushEnabled:true,draftRetentionDays:7});const context=createDevelopmentRequestContext();expect(await service.registerDevice(context,input)).toMatchObject({status:"pending",trustLevel:"unmanaged"});expect((await service.bootstrap(context,input.installationId,"0.9.0")).features).toEqual({offlineDrafts:false,push:false});});
  it("enforces ownership and revokes push capability with the device",async()=>{const repository=new InMemoryClientPlatformRepository();const service=new ClientPlatformService(repository,{minimumVersion:"0.9.0",managedDeviceRequired:false,offlineDrafts:"disabled",pushEnabled:true,pushPublicKey:"public",draftRetentionDays:7});const owner=createDevelopmentRequestContext();const device=await service.registerDevice(owner,input);await service.subscribe(owner,device.id,{endpointDigest:"a".repeat(64),encryptedPayload:"cipher",initializationVector:"iv",authenticationTag:"tag",keyRef:"secret://client/key"});const other={...owner,actorId:"10000000-0000-4000-8000-000000000099",permissions:owner.permissions.filter(permission=>permission!=="client:device:admin")};await expect(service.revoke(other,device.id)).rejects.toThrow("POLICY_DENIED:client:device:ownership");expect(await service.revoke(owner,device.id,new Date("2026-08-05T01:00:00Z"))).toMatchObject({status:"revoked",pushEnabled:false});expect([...repository.subscriptions.values()][0]).toMatchObject({status:"revoked"});await expect(service.registerDevice(owner,input)).rejects.toThrow("CLIENT_DEVICE_REVOKED");});
  it("compares semantic versions and encrypts sensitive push material with bound context",()=>{expect(compareVersions("0.10.0","0.9.9")).toBe(1);const key=crypto.getRandomValues(new Uint8Array(32));const envelope=encryptSensitiveJson({endpoint:"https://push.example/private"},Buffer.from(key),"tenant:user:device");expect(JSON.stringify(envelope)).not.toContain("push.example");expect(decryptSensitiveJson(envelope,Buffer.from(key),"tenant:user:device")).toEqual({endpoint:"https://push.example/private"});expect(()=>decryptSensitiveJson(envelope,Buffer.from(key),"other-context")).toThrow("ENCRYPTED_ENVELOPE_INVALID");expect(sensitiveValueDigest("https://push.example/private")).toHaveLength(64);});
  it("encrypts Internal offline drafts without plaintext indexes and rejects higher classifications",async()=>{const key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);const draft={id:crypto.randomUUID(),title:"华东风险草稿",body:"仅供离线编辑的虚构内容",classification:"internal" as const,createdAt:"2026-08-05T00:00:00.000Z",expiresAt:"2026-08-12T00:00:00.000Z"};const stored=await encryptOfflineDraft(draft,key);expect(JSON.stringify(stored)).not.toContain("华东");expect(await decryptOfflineDraft(stored,key)).toEqual(draft);await expect(encryptOfflineDraft({...draft,classification:"confidential" as never},key)).rejects.toThrow("OFFLINE_CLASSIFICATION_DENIED");});
});
